### ISSUE TITLE
I am having some connection issues testing this plug in.

### ISSUE THREAD

**Issue by purringpigeon** [FibreFoX/javafx-gradle-plugin#10]
I do not believe they are your side - just wanted you to know why I hadn't posted back success or failure.

Thanks.

**Comment by FibreFoX** [comment]
Hm ... i never head some for me. Maybe it's your connection? Do you have something to reproduce this?

Just to inform you, when it's not a direct but, please send me some e-mail to fibrefox@dynamicfiles.de, as it wouldn't put wrong issues on github.
