### ISSUE TITLE
Adding extensions to wix

### ISSUE THREAD

**Issue by pupeno** [FibreFoX/javafx-gradle-plugin#101]
Hey there,

Is it possible to add extensions to wix when using javafx-gradle-plugin? 

https://stackoverflow.com/questions/48711876/adding-extension-libraries-to-wix-when-using-the-javafx-packager

**Comment by FibreFoX** [comment]
To add the question from SO here too:

> According to the Wix documentation, by adding `-ext WixUIExtension -ext WixUtilExtension` to the command line (...)

After looking into the responsible msi-bundler, I found this fragment:
```java
List<String> commandLine = new ArrayList<>();

// (...)
commandLine.add("-ext");
commandLine.add("WixUtilExtension");
if (enableLicenseUI || enableInstalldirUI) {
    commandLine.add("-ext");
    commandLine.add("WixUIExtension.dll");
}

// (...)
```

This means `WixUtilExtension` is always added, and when having the user to choose the installation target directory, the extension `WixUIExtension` gets added too.

To have the user choose the target installation directory, you have to set this inside the jfx-configuration-part:
```groovy
jfx {
// ...
    bundleArguments = [
        'installdirChooser': true
    ]
// ...
}
```

**Comment by FibreFoX** [comment]
ping @pupeno

**Comment by pupeno** [comment]
This worked. Thank you very much! :)
