### ISSUE TITLE
Error when running on a container

### ISSUE THREAD

**Issue by Pesegato** [FibreFoX/javafx-gradle-plugin#104]
To work around issue #102 , I've tried turbo.net (it provides a containerized environment that allows me to run safely apps on forbidden folder).

After installing it, I run
`turbo run oracle/jdk:8.0 --mount=%CD%`

then I do my gradle stuff. But it stops with this error:

```
> Task :jfxJar
Putting task artifact state for task ':jfxJar' into context took 0.0 secs.
Executing task ':jfxJar' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Adding 'deploy' directory to classpath: src/main/deploy

:jfxJar (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jfxJar'.
> com/oracle/tools/packager/Log$Logger
```

debug Log: https://pastebin.com/E5YAExYf
stacktrace: https://pastebin.com/NNB1dj7k

**Comment by FibreFoX** [comment]
Hm ... these problems are mostly because there is some OpenJDK used and OpenJFX is not yet installed. Maybe the container is not yet configured to take the OracleJDK?

**Comment by Pesegato** [comment]
On the container, if I run java -version I get

```
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)
```

**Comment by Pesegato** [comment]
Also:
javafxpackager -version

    JavaFX Packager version 2.2

**Comment by FibreFoX** [comment]
Hm ... what does `gradle -version` say about the JDK?

**Comment by Pesegato** [comment]
I'm using the gradle wrapper.

gradlew -version

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0 (Oracle Corporation 25.0-b70)
OS:           Windows 7 6.1 x86

**Comment by FibreFoX** [comment]
Dang ... I was hoping the image just was misconfigured.

**Comment by Pesegato** [comment]
Anything that I can do to help?

**Comment by Pesegato** [comment]
Solved! I used the "jdk64" image instead of the "jdk" (32 bit) and everything works! :)

**Comment by FibreFoX** [comment]
Thanks for reporting back :D I feared to use "turbo" for reproducing, happily you found it. Thanks for sharing!
