### ISSUE TITLE
Is it possible to change the name of the main launcher?

### ISSUE THREAD

**Issue by pupeno** [FibreFoX/javafx-gradle-plugin#105]
Hello,

Is it possible to change the name of the main launcher but keep the appName the way it is?

**Comment by FibreFoX** [comment]
Can you define more precicely what you mean with "main launcher"?

**Comment by pupeno** [comment]
I mean, the entry on the start menu (aside from secondary launchers).

**Comment by FibreFoX** [comment]
I'm on the road, will check later

**Comment by pupeno** [comment]
Thank you :)

**Comment by pupeno** [comment]
I tried setting up

```
needMenu = false
```

and then just have all my launchers be secondary launchers. But it looks like needMenu is not preventing the native menu entry from getting created.

**Comment by pupeno** [comment]
I also tried:

```
needShortcut = false
```

to no avail.

**Comment by FibreFoX** [comment]
When using `EXE`-installer, you might be able to change this inside the `src/main/deploy/windows/{appName}.iss`-file, by changing this lines:
```ini
[Icons]
Name: "{group}\APPLICATION_NAME"; Filename: "{app}\APPLICATION_NAME.exe"; IconFilename: "{app}\APPLICATION_NAME.ico"; Check: APPLICATION_MENU_SHORTCUT()
 ```
Changing the `Name:`-part should be sufficiant.

For `MSI`-installer I'm still searching, but does not look like being possible :(

**Comment by pupeno** [comment]
Thank you. I'm doing a completely different workaround, so, I'm closing this to avoid wasting any of your time.
