### ISSUE TITLE
Missing MSVCR100.dll

### ISSUE THREAD

**Issue by chineseboytom** [FibreFoX/javafx-gradle-plugin#108]
Thank you for your great work！
When I build native application with version 8.8.2 in Windows 7, encounter the "Missing MSVCR100.dll" error.
![image](https://user-images.githubusercontent.com/6320605/37099213-c4961e66-225a-11e8-850a-f1107b89755a.png)

**Comment by FibreFoX** [comment]
What JDK version do you use?

**Comment by chineseboytom** [comment]
I use jdk1.8.0_161.

**Comment by FibreFoX** [comment]
This is some JDK-bug, nothing related to this gradle-plugin. See also: https://bugs.openjdk.java.net/browse/JDK-8126704

Seems that on Windows 7 there is something required, like Visual C++ runtime, but nothing I can do to workaround this, sorry.

**Comment by chineseboytom** [comment]
Thank you! This JDK-bug has been fixed in jdk1.8.0_162.
