### ISSUE TITLE
Package regular app

### ISSUE THREAD

**Issue by valnaumov** [FibreFoX/javafx-gradle-plugin#111]
Is it possible to package a regular Java app (with `public static void main(String[] args)`) with the plugin?

I have tried, the jfxRun generates a proper jar that prints a "Hello World", but launching an exe gives no output at all. How can I debug it?

I am in need of a Gradle plugin that would bundle a JRE for Mac and Windows, thought this would work, but if it does not, can you offer advice? Thanks.

**Comment by FibreFoX** [comment]
As far as I can tell, there is nothing special about javafx when using the `javapackager` or this gradle-plugin, but I might not know how native launchers are working. Executables on Windows can come with two flavors: GUI or Console-application. This means every "System.out.println" will NOT get written to the console, you have to use your own favorite logger-framework and create some file-log. Per default the provided EXE-launcher is NO Console-application, please see this for more information: https://github.com/FibreFoX/javafx-gradle-plugin/issues/72
