### ISSUE TITLE
Volume icon not applied

### ISSUE THREAD

**Issue by schw4rzlicht** [FibreFoX/javafx-gradle-plugin#118]
I am trying to package a `.dmg` and set up custom icons for the app and the volume. While the app icon works, the `.dmg` icon is never applied.

Sometimes I get `Exec failed with code 2 command [[/usr/bin/SetFile, -c, icnC, /var/folders/7p/_bz4z7fx2592wbjc9zwmr7m00000gn/T/fxbundler5347395258233525975/images/Applause-O-Meter/.VolumeIcon.icns] in unspecified directory` during build but this is not reproducible.

What I also noticed is that icons inside the `.dmg` are always placed out of the visible canvas:<img width="629" alt="bildschirmfoto 2018-04-12 um 16 08 23" src="https://user-images.githubusercontent.com/19175262/38682601-cb90af60-3e6b-11e8-8e29-bb8f3b3ed5f8.png">
I am using Gradle 4.6, macOS 10.13.4, JDK 1.8.0_162 with plugin version 8.8.2.

What am I missing?

**Comment by FibreFoX** [comment]
Maybe you are hitting some size-restrictions. I'm sorry, I'm not a mac-user myself, but often its the formfactor, or the image dimension. Not really sure how to help you here.
