### ISSUE TITLE
Icon is not picked up

### ISSUE THREAD

**Issue by CookieHoodie** [FibreFoX/javafx-gradle-plugin#129]
My 'appName' is 'osc' and I got from README that I have to put my icon 'osc.ico' in 'src/main/deploy/package/windows/osc.ico' in order to be picked up. BUT it is not... The console keep showing me "Using default package resource [icon]  (add package/windows/osc.ico to the class path to customize)" when I set verbose to true.

Very sure there's no typo, and I've tried putting it in 'src/main/package/windows/osc.ico', 'deploy/package/windows/osc.ico', 'package/windows/osc.ico', all to no avail.

Any help?

**Comment by FibreFoX** [comment]
Sounds strange, have you a normal project or a multi-module project? Having that file at `src/main/deploy/package/windows/osc.ico` should work fine. Maybe something with filesystem rights?

**Comment by CookieHoodie** [comment]
It's just a normal testing project before I integrate it into my real project, which is also a normal one.
Here is the screenshot:

![screenshot 13](https://user-images.githubusercontent.com/15065550/43674018-5f498122-97ff-11e8-9e7d-e07eece97a43.png)

**Comment by FibreFoX** [comment]
Oh, you missed to mention this happening on JDK 9 ;) which version of the plugin are you using?

**Comment by CookieHoodie** [comment]
Yea I'm using JDK 9 but I tried to change to JDK 8 the same thing happened..
I'm using version 8.8.2 and Gradle 4.8.
Maybe caused by gradle version?

**Comment by CookieHoodie** [comment]
Ok I tried using Gradle version 2.10 but with the same result.
I also tried to run it in command line instead of Intellij.

Btw, I encountered another error when I tried to add a dependency to the project:
`Exception: java.nio.file.NoSuchFileException: C:\Users\xxx\Desktop\testGradleBuild\build\jfx\app\lib\sqlite-jdbc-3.23.1.jar -> C:\Users\xxx\Desktop\testGradleBuild\build\jfx\native\osc\app\lib\sqlite-jdbc-3.23.1.jar`
What's the problem here?

**Comment by FibreFoX** [comment]
Thats odd, sorry. Can you provide some small project for me where I can re-produce this?

**Comment by CookieHoodie** [comment]
I've uploaded the exact project I screenshot to [my repo](https://github.com/CookieHoodie/test-gradle-build), you can clone it there. Thanks for helping btw :)

**Comment by FibreFoX** [comment]
Thanks for that, I've found the problem: since the final JDK 9 release, they changed the way how that deploy-folders gets picked up. You have to change your configuration a bit:
```groovy
    bundleArguments = [
            installdirChooser: 'true',
            dropinResourcesRoot: './src/main/deploy' // required since JDK9 :/ sadly
    ]
```

To have the plugin working, you might want to use a later snapshot-version:
```groovy
buildscript {
    dependencies {
        classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: '8.9.0-SNAPSHOT'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}
```

**Comment by CookieHoodie** [comment]
I was DUMB lol I thought I had changed to JDK 8 but actually didn't. Now I try using JDK 8 and everything works fine.

So for JDK 9 after changing to above settings the icon is finally correctly picked up, but the `java.nio.file.NoSuchFileException` is still showing.

**Comment by FibreFoX** [comment]
I never got that exception using the `8.9.0-SNAPSHOT` version running on JDK 10. You should upgrade to JDK10 too, as JDK9 just was simply a intermediate release.

**Comment by CookieHoodie** [comment]
Okay, haven't tried that but the solution seems legit. Thanks for your help and patience! Closing.
