### ISSUE TITLE
Wrong path while usage on multi-project

### ISSUE THREAD

**Issue by FibreFoX** [FibreFoX/javafx-gradle-plugin#13]
While helping @purringpigeon we discovered some difference on multi-project builds:

The current folder isn't the expected one, currently the root-project needs to contain `src/main/deploy`, which isn't the wanted behaviour!

**Comment by FibreFoX** [comment]
Hi @purringpigeon, could you test my changes with your multi-project buildfile? This should change the thing we discovered while mailing.

**Comment by purringpigeon** [comment]
Yes. I will test it now. Do I need to change the version number?

On Jan 26, 2016, at 1:41 PM, Danny Althoff <notifications@github.com> wrote:

Hi @purringpigeon, could you test my changes with your multi-project buildfile? This should change the thing we discovered while mailing.

**Comment by FibreFoX** [comment]
@purringpigeon I uploaded a new SNAPSHOT-Version:
```groovy
buildscript {
    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: '1.1-SNAPSHOT'
    }
}
```

**Comment by FibreFoX** [comment]
As discussed on issue #12 this should be working now (still remains that clean-bug, but this one should get closed)
