### ISSUE TITLE
Deb package throws "ValidatorException: No trusted certificate found"

### ISSUE THREAD

**Issue by klassm** [FibreFoX/javafx-gradle-plugin#131]
When creating and running a deb package and downloading some URL afterwards, like
```
new URL(...).openStream(...)
```
a ValidatorException will be thrown, as no trusted certificate can be found. When staring the application using `./gradlew jfxRun`, the code works and trusted certificates will be found.
Am I doing something wrong? What's the correct way to handle certificates here?
Thanks,
Matthias

**Comment by FibreFoX** [comment]
Looks like you are shipping your application with a bundled JRE where that certificate is not trusted yet. When running via `./gradlew jfxRun` the java-process of the gradle-daemon will get used, which might have a different truststore-setting.

**Comment by klassm** [comment]
Well - this is using default certificates. There's nothing special imported for the running JVM. So the bundled JRE should also be able to cope with it, right?
Do I have to specify each CA I want to trust?

**Comment by FibreFoX** [comment]
@klassm  Which JDK are you using for this?

**Comment by klassm** [comment]
@FibreFoX That's JDK8:
╰─$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

To be honest, I didn't try another one :-) But normal trusted CAs should be available by default, right? I mean - I have no idea how I can get around this currently. For sure, I can specify my own trust store, but then I'd have to replicate the whole trusted CAs of the system.

**Comment by FibreFoX** [comment]
They changed the provided truststore in JDK 9 + 10:
https://bugs.openjdk.java.net/browse/JDK-8189356
https://bugs.openjdk.java.net/browse/JDK-8189131

This is not an issue of this plugin, more a usage-problem of the bundled JRE. In addition it is possible to "ignore" security (but only as last resort).

**Comment by klassm** [comment]
Oh I see - so I just need to upgrade to JDK 9 / 10 - then it should at least behave the same way on development as on the binary. Thanks, I'll try that :-)
