### ISSUE TITLE
Javafx native app not working on Windows x32

### ISSUE THREAD

**Issue by Dahaka934** [FibreFoX/javafx-gradle-plugin#134]
Hello.
I created simple app from example and built its. build.gradle also taken from example. But this app not working on PC with Windows 7 x32. Also I tested it on virtual machine. Java is not installed. But this app normal works on clean Windows 7 x64.

**Comment by abaker** [comment]
You need to use an x86 JDK if you need your app to run on 32-bit Windows (e.g. Oracle jdk-8u*-windows-i586.exe)

**Comment by FibreFoX** [comment]
This is a restriction from the underlying javapackager, you need to build your app for each targeted platform, using the same platform-type as build-system.
