### ISSUE TITLE
Question on logging during jfxNative

### ISSUE THREAD

**Issue by purringpigeon** [FibreFoX/javafx-gradle-plugin#14]
Hello,

Thanks for the update to 1.3.  We have rolled this out to our development team.  Thanks for this plug in.  I keep seeing this at the end of the build:

```
Detected [candle.exe] version 0 but version 3 is required.
Detected [light.exe] version 0 but version 3 is required.
```

I am not sure what that is, or if I should be worried about them?  

Thanks

**Comment by FibreFoX** [comment]
If you set verbose to `true`, there might be some more output. The output comes from some version-checking of installed "WiX Toolkit", if you are using the up2date version (currently 3.10) the bundler isn't finding that files:
http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinMsiBundler.java#l143
http://hg.openjdk.java.net/openjfx/8u/rt/file/642a0d0d4767/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinMsiBundler.java#l143

The message you are getting, mostly say "you haven't installed WiX Toolki", as far as I can see:
http://hg.openjdk.java.net/openjfx/8u/rt/file/642a0d0d4767/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinMsiBundler.java#l258

If you are generating EXE-installer, everything is okay, if you want to create MSI-installer, you shouldn't get some installer ;)

**Comment by FibreFoX** [comment]
Oh, and add `--info` to gradle command ;) there is more output from the gradle-plugin too.

**Comment by FibreFoX** [comment]
@purringpigeon If the answer satisfies you, please close the issue yourself ;)

**Comment by purringpigeon** [comment]
Thanks!
