### ISSUE TITLE
Multi project application - icon is not used

### ISSUE THREAD

**Issue by Rykee** [FibreFoX/javafx-gradle-plugin#148]
Hello!

Recently I changed my single project application to a multi project one.  
After the change the jfxNative task can't find the ico file for the exe.  
I ran the task with an --info argument, and found out that the deploy dir is found, but the ico file is not.

> Adding 'deploy' directory to classpath: src/main/deploy
> Using default package resource [icon]  (add package/windows/Supervisor.ico to the class path to customize)

Relevant configurations:

> Using default package resource [icon]  (add package/windows/Supervisor.ico to the class path to customize) 
    bundleArguments = [
            installdirChooser  : 'true',
            dropinResourcesRoot: './src/main/deploy'
    ]
    appName = "Supervisor"  

Gradle version: 5.5.1 using wrapper

What is weird that the additionalfiles are picked up, and copied, but the ico cannot be found.
Is it possible to log out the path where the plugin is looking for the ico file?
Any suggestions?

Thanks for the help.

Cheers

**Comment by Rykee** [comment]
Bump?

**Comment by FibreFoX** [comment]
Why did you use `dropinResourcesRoot` here? Normally this should not be relevant that much, but you need the "correct" folder structure, and be aware that `./src/...` is relative, and might be "wrong". Did you try to remove `dropinResourcesRoot` and having that icon in `src/main/deploy/package/windows/Supervisor.ico`?

**Comment by FibreFoX** [comment]
@Rykee bump 2 ;)

**Comment by Rykee** [comment]
Sorry wasn't working on the project recently.
If I remove the dropinResourcesRoot it doesn't find the icon either.
But now with a simple 'src/main/deploy' it works. (without the dot).
If I remember correctly I tried that before, and it didn't work, but now it does.  ¯\_(ツ)_/¯
