### ISSUE TITLE
Plugin doesn't bundle runtime dependencies into app/lib/

### ISSUE THREAD

**Issue by sleonidy** [FibreFoX/javafx-gradle-plugin#15]
I have created sample project for demonstrating the issue
[javafxplugin.zip](https://github.com/FibreFoX/javafx-gradle-plugin/files/172042/javafxplugin.zip)

**Comment by purringpigeon** [comment]
If you have this set:

bundleArguments = [
        // dont bundle JRE (not recommended, but increases build-size/-speed)
        runtime: null
    ]
It will not bundle the runtime - I have that removed from my build and it works fine.

**Comment by FibreFoX** [comment]
@sleonidy Will have to take a look :)

**Comment by sleonidy** [comment]
I didn't set this option(Cause I want jre to be bundled), what I mean is:
If you add dependency to gradle to runtime scope , it won't bundle it.
Take a look at a project I've attached.
Thanks

**Comment by FibreFoX** [comment]
@sleonidy I'm already seeing your issue, will have to take a look how to fix this and why it's there

@purringpigeon the issue is about runtime-dependency, not the runtime itself :smile:

**Comment by FibreFoX** [comment]
@sleonidy Might have found the confusion here:
you are setting your dependency into the scope **"runtime"**, but this plugin works with scope **"compile"**, so thats the reason why no lib is copied.

Will have to take a look into the maven-plugin if it is possible to add something for runtime-dependencies too.

Quick workaround: 
```groovy
dependencies {
    compile 'org.slf4j:slf4j-api:1.7.16'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}
```

**Comment by FibreFoX** [comment]
@sleonidy Hi, I've checked the javafx-maven-plugin for this behaviour, seems that this is a real bug ;) thanks for finding this. I will create a quick fix and will report back when having something for you.

**Comment by FibreFoX** [comment]
@sleonidy could you try with version `8.4.1-SNAPSHOT` using Sonatype-Snapshot-Reposiroty?

```groovy
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: '8.4.1-SNAPSHOT'
    }
}
```

**Comment by sleonidy** [comment]
It is working .
Thanks for quick fix.

**Comment by FibreFoX** [comment]
@sleonidy just to make sure, you used the new version instead of switching "runtime" to "compile", right?

The new 8.4.1 should be available through maven-central in the next few days.

**Comment by sleonidy** [comment]
Yes. I've checked that "runtime" dependencies are copied to app/lib folder .
