### ISSUE TITLE
Couldn't find Ant-JavaFX-Library

### ISSUE THREAD

**Issue by twyatt** [FibreFoX/javafx-gradle-plugin#16]
First off, thanks for this awesome Gradle plugin!

Currently running into an issue on Windows 7 SP1:

Running `gradlew.bat jfxRun` results in:
```
* Where:
Build file 'test/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating project ':test'.
> Failed to apply plugin [id 'javafx-gradle-plugin']
   > Couldn't find Ant-JavaFX-Library, please make sure you have JDK (with JavaFX) installed.
```

I was able to fix the problem by copying `ant-javafx.jar` from my `Program Files\Java\jdk1.8.0_77\lib` to `Program Files\Java\lib` folder.

I believe [Line 89](https://github.com/FibreFoX/javafx-gradle-plugin/blob/8.4.1/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/JavaFXGradlePlugin.java#L89) of [JavaFXGradlePlugin.java](https://github.com/FibreFoX/javafx-gradle-plugin/blob/8.4.1/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/JavaFXGradlePlugin.java) should have been used for this version of Java (not sure which version of Java introduced this changed)?

Perhaps it would work to search for the `ant-javafx.jar` file at one location, and if not found there, then try the alternate location (rather than relying on Java version)?

```
> java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

```
> javac -version
javac 1.8.0_77
```

Thanks!!!

**Comment by FibreFoX** [comment]
Hi there,

thanks for using my fresh gradle plugin :smile_cat: 

It's just a thought, but could you check what JAVA_HOME is set? It should be the JDK, not the JRE. The JDK has a different structure with the libs than the JRE has.

For better support I will think about some diagnostic task for copy&pasting it here ;)

**Comment by twyatt** [comment]
Admittedly, I don't use Windows very often, so I had completely overlooked setting `JAVA_HOME`:
```
> echo %JAVA_HOME%
%JAVA_HOME%
```

I had installed the JDK and JRE just prior to running the `jfxRun` Gradle task.

I removed the extra copy I had made of `ant-javafx.jar` and setting the `JAVA_HOME` did resolve the issue:
```
> set JAVA_HOME="C:\Program Files\Java\jdk1.8.0_77"
```

But that leaves me to wonder what `JAVA_HOME` defaulted to when not defined? Perhaps it was using `C:\Program Files\Java` as my `JAVA_HOME` path? That would seem odd, but having `ant-javafx.jar` copied to `C:\Program Files\Java\lib` worked.

Here is a directory listing of my `C:\Program Files\Java` directory using the `dir /s /b` command:
[java_dir.txt](https://github.com/FibreFoX/javafx-gradle-plugin/files/187531/java_dir.txt)

Hopefully that is helpful.

**Comment by FibreFoX** [comment]
@twyatt No problem, glad to help here.

The default is just "empty", it's a normal windows-installation-procedure to set that variable BEFORE using tools.

The structure in JDK9 is different than JDK8, for that my switch in [Line 88](https://github.com/FibreFoX/javafx-gradle-plugin/blob/8.4.1/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/JavaFXGradlePlugin.java#L88) was made for.

There is NO NEED for having some action to be taken on my side, because setting JAVA_HOME is a default-task regarding java-development on windows. Even a lot of programs on linux require that env-variable to be set.

But I'm happy it is working for you now.
