### ISSUE TITLE
Please add example how to add fileAssociations to application

### ISSUE THREAD

**Issue by KorvinGump** [FibreFoX/javafx-gradle-plugin#17]
What should i add to line in gradle build script
`fileAssociations = null // List<Map<String, Object>>`
I know that you have class [FileAssociation](https://github.com/FibreFoX/javafx-gradle-plugin/blob/master/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/converter/FileAssociation.java). But where i must create this object and how to add it to gradle build script? Please add example how to add fileAssociations to application.

**Comment by FibreFoX** [comment]
This should work
```groovy
fileAssociations = [
    [
        "description": "some description",
        "extensions": "ext",
        "contentType": "application/dummy",
        "icon": new File(somePathToIcon)
    ]
]
```

**Comment by KorvinGump** [comment]
I am getting exception.
```
* What went wrong:
Execution failed for task ':jfxNative'.
> java.io.File cannot be cast to java.lang.String
```
So, how to create file if it allows only String?

**Comment by FibreFoX** [comment]
@KorvinGump are you sure you have wrapped `somePathToIcon` with `new File()`?

**Comment by FibreFoX** [comment]
@KorvinGump I'll make a working example locally :) might take some while, but I will provide working example here.

**Comment by FibreFoX** [comment]
@KorvinGump Hi, sorry for that non-working suggestion from me ;) I was too long out of this plugin.

Please have a look at this:
```groovy
jfx {
    verbose = true
    mainClass = 'org.company.appname.Launcher'
    appName = 'appname'
    manifestAttributes = [
        version: "Build 1.0"
    ]
    jfxMainAppJarName = 'appname.jar'
    vendor = "My Company"
    bundleArguments = [
        runtime: null
    ]
    fileAssociations = [
        [
            description: "some description",
            extensions: "ext",
            contentType: "application/dummy",
            icon: "PathToIconAsString.ico"
        ],
        [
            description: "some description 2",
            extensions: "ext2",
            contentType: "application/dummy2",
            icon: "PathToIconAsString.ico"
        ]
    ]
}
```

This worked for me locally, I hope it works for you too!

**Comment by KorvinGump** [comment]
It works! But i installed latest version of [Inno Setup](http://www.jrsoftware.org/isdl.php). Now gradle build creates .EXE installer for me. It's good. Don't know but can i configure inno setup script, so i can add installation folder and other params, such as language, etc? We really need a documentation... Thanks for your help.

**Comment by FibreFoX** [comment]
It works like normal javapackager (and like with javafx-maven-plugin), just create `src/main/deploy` with the override-scripts you like, when having `verbose` set to `true` (and expecially passing `--info `-parameter when calling gradle), you will get some folder where your generated .wxs/.wxi-files are stored.
Please remember: this plugin is just a gradle-wrapper for the tools provided by the JDK itself. To add more folders/files than they are generated by the native bundler (before generating installers), you can provide some folder-structure setting `additionalAppResource`, that files and folders will be copied afterwards to the generated target (`build/jfx/native`).

As the original question was now answered, I'll close this issue. For some questions, just drop me some email.
