### ISSUE TITLE
How can I add a JVM argument?  

### ISSUE THREAD

**Issue by purringpigeon** [FibreFoX/javafx-gradle-plugin#18]
I have attempted to add the following argument:

-Dglass.win.minHiDPI=1.0

I tried like this:
`jvmArgs=Dglass.win.minHiDPI=1.0`

Throws the error:

FAILURE: Build failed with an exception.
 
* Where:
Build file 'C:\workspace\alpha-powersuiteui\powersuitefx-master-module\powersuite-app\build.gradle' line: 72
 
* What went wrong:
A problem occurred evaluating project ':powersuite-app'.
> Could not find property 'Dglass' on de.dynamicfiles.projects.gradle.plugins.javafx.JavaFXGradlePluginExtension_Decorated@79b18230.
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I tried it like this
`jvmArgs=-Dglass.win.minHiDPI=1.0`

Throws the error: 

FAILURE: Build failed with an exception.
 
* Where:
Build file 'C:\workspace\alpha-powersuiteui\powersuitefx-master-module\powersuite-app\build.gradle' line: 72
 
* What went wrong:
Could not compile build file 'C:\workspace\alpha-powersuiteui\powersuitefx-master-module\powersuite-app\build.gradle'.
> startup failed:
  build file 'C:\workspace\alpha-powersuiteui\powersuitefx-master-module\powersuite-app\build.gradle': 72:
class org.codehaus.groovy.ast.expr.UnaryMinusExpression, with its value 'Dglass.win.minHiDPI', is a bad expression as the left hand side of an assignment operator at line: 72 column: 33. File: build_a
ev6tgo7bsafrdrlt83pi2056 @ line 72, column 33.
         jvmArgs=-Dglass.win.minHiDPI=1.0

**Comment by purringpigeon** [comment]
I found the way:

jvmArgs=["-Dglass.win.minHiDPI=1.0"]

**Comment by FibreFoX** [comment]
I'm glad you found the way :smile_cat: it's the groovy-way of handling string-lists.
