### ISSUE TITLE
Doesn't seem to have a way to set the category for the native install

### ISSUE THREAD

**Issue by swpalmer** [FibreFoX/javafx-gradle-plugin#20]
How do we set stuff like category and copyright?

https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/javafx_ant_task_reference.html#CIAIEJHG

**Comment by FibreFoX** [comment]
Hi @swpalmer,

this is some argument for the bundler so this is dependend on the build system (operating system) and the bundler to work with.

```groovy
jfx {
    // ...
    bundleArguments: [
    ]
    // ...
}
```

To give you a more proper answer, what OS are you using? Windows? MacOSX? Linux?

**Comment by FibreFoX** [comment]
To find the names for the arguments are listed [inside the BundleParams.java-file as seen in the OpenJDK](https://github.com/teamfx/openjfx-8u-dev-rt/blob/fd634925571310284b02d89ff512552e795ba5e8/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/bundlers/BundleParams.java#L63)

```groovy
jfx {
    // ...
    bundleArguments: [
        "copyright": "your copyright string with limitations",
        /* Application category. Used at least on Mac/Linux. Value is platform specific */
        "applicationCategory": "yourCategory"
    ]
    // ...
}
```

**Comment by FibreFoX** [comment]
ping @swpalmer

**Comment by FibreFoX** [comment]
What is a `GString`, never heard of in Java-context?

The consistency here is that some things are shared among all bundlers, as this gradle-plugin has it's roots at the javafx-maven-plugin, this was intended to give the most easy way for "maven to gradle"-transition.

Just to make the state of this issue clear: does the given answer work for you? If so, please close this issue, we still can sort out the remaining parts, if you like ;)

**Comment by swpalmer** [comment]
Gradle is based on Groovy.  GString is Groovy .. let's you do "blah ${project.name}" and have the substitution happen.

**Comment by FibreFoX** [comment]
Yes, this plugin expects normal `java.lang.String` instead of `groovy.lang.GString`, to workaround just add some `.toString()` to these values. It is more a convenience-thing instead of a real bug. :smiley_cat: but thanks for the clarification, didn't knew that thing before.

**Comment by FibreFoX** [comment]
Oh, about that "menu-entry" you talked about, take a look at the [WindowsBundlerParam-class](https://github.com/teamfx/openjfx-8u-dev-rt/blob/fd634925571310284b02d89ff512552e795ba5e8/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WindowsBundlerParam.java#L81), the `bundleArguments`-name is "win.menuGroup", and please [set the needMenu-parameter](https://github.com/FibreFoX/javafx-gradle-plugin/blob/e41cc4daa37edd9b5673188be93e967cd9c83b61/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/JavaFXGradlePluginExtension.java#L55)
```groovy
jfx {
// ...
 needMenu: true` 
// ...
```
