### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by siavashkavousi** [FibreFoX/javafx-gradle-plugin#21]
I've just built your example with *gradle jfxRun* and I've got this error

Error: Could not find or load main class com.zenjava.test.javafx_and_proguard.MainApp

Before that, I've tried on my own project using your plugin and I've got the same error

**Comment by FibreFoX** [comment]
Hi @siavashkavousi , I'm very sorry, but I can't reproduce this. Please make sure to have latest OracleJDK installed.

To make some progress here, please execute gradle with additional parameter and post the result here:
```
gradle jfxRun --info
```

**Comment by siavashkavousi** [comment]
Problem was JDK, I was using openJDK ...

why does it need to be oracleJDK?

Anyway thanks for your answer

**Comment by FibreFoX** [comment]
You need the OracleJDK or OpenJDK+OpenJFX, only OpenJDK isn't sufficient.
