### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by FabianSchmiedlechner** [FibreFoX/javafx-gradle-plugin#23]
Hey, I just stumbled over your project when I saw your post in one of the issues of this project - https://bitbucket.org/shemnon/javafx-gradle 
Unfortunately this project is no longer maintained. It had some bugs but it created a relatively fine windows-installer for me.
I just got the jfxNative task of your project running from outside the IDE but it does not create a windows-installer.exe. Can I do this with this library or do I have to create the installer manually?

Cheers,

**Comment by FibreFoX** [comment]
Hi @FabianSchmiedlechner, this gradle-plugin is a convenient-wrapper for the javapackger, so you can [visit the official documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#A1324980) to know about the requirements on each operating-system.

To be able to create some installer on windows, you have to install [WiX Toolset](http://wixtoolset.org/) or [Inno Setup](http://www.jrsoftware.org/). To have more information about the internal tooling, you can set verbose-mode and add some gradle-parameter: `gradle clean jfxNative --info`

to make this plugin work, you have to apply it to your buildscript inside "jfx"-configuration (like visible in the readme-file or example-projects).

Hopefully this does clear some questions. To keep this issue-tracker as clean as possible, just send me some email to my address (visible on my github-profile-page).

**Comment by FibreFoX** [comment]
Closing this, as there is no bug here.
