### ISSUE TITLE
Add obfuscation like proguard

### ISSUE THREAD

**Issue by Burtan** [FibreFoX/javafx-gradle-plugin#28]
Hi, 
what do you think about adding the possibility to obfuscate your code with apps like proguard?
Thanks for consideration!

**Comment by FibreFoX** [comment]
You mean something like this?
https://github.com/FibreFoX/javafx-gradle-plugin/tree/master/examples/javafx-proguard-gradle

That example is target of changes, when having https://github.com/FibreFoX/javafx-gradle-plugin/issues/26 fixed/changed.

**Comment by Burtan** [comment]
Thanks for the fast response, I'll look into it :+1:

**Comment by FibreFoX** [comment]
No problem, just saw your request. Please close the issue, when you found the example working for you.

**Comment by FibreFoX** [comment]
@Burtan please reopen, if you need support/help, or the example isn't working out for you ;)
