### ISSUE TITLE
System.out/err and jfxRun

### ISSUE THREAD

**Issue by embee1981** [FibreFoX/javafx-gradle-plugin#29]
Daft question but how do you get jfxRun to show output from System.out/err?

On running via this task, my app had an expected fatal crash and I get shown

```
Running JavaFX Application
:jfxRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jfxRun'.
> There was an exception while executing JavaFX Application. Please check build-log.
```
I can't find build-log to see the stack trace from the exit and was wondering how I can get it to show all std out/err stuff to the gradle console?

**Comment by FibreFoX** [comment]
Hi @embee1981 , first of all: thanks for using my gradle-plugin.

The jfxRun-task uses [the inheritIO-call of the ProcessBuilder](https://github.com/FibreFoX/javafx-gradle-plugin/blob/7a354e2a711b42d5c52ef9d44de03805f1217426/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/tasks/JfxRunTask.java#L52), so you should see any output, which is done.

To make sure you really are having "no output", please call `java -jar your-app-name.jar` inside the `build/jfx/app/`-folder ... maybe your application just can't start correctly or even does no output?!

**Comment by embee1981** [comment]
Hiya, yeah I'm getting output when running via java -jar :-(

Java version is 1.8.0_92 and Gradle is 3.0  (forgot to give some version info in first post)

**Comment by FibreFoX** [comment]
Hm .... that sounds strange ... but maybe because of gradle 3.0 ...
Do you have the time/chance to create some minimal reproducable project to share with me? With that I can debug that.

**Comment by embee1981** [comment]
Sure 
[JavaFxPluginDemo.zip](https://github.com/FibreFoX/javafx-gradle-plugin/files/427987/JavaFxPluginDemo.zip)

Simple IDE agnostic project attached :-)
 The App class attempts a sys out, sys err and throws a runtime exception to exit.

I'm on Windows 10, 64 bit version as well in case that's a factor.

**Comment by FibreFoX** [comment]
Thanks, will check it out now 👍

**Comment by FibreFoX** [comment]
As gradle 3 now uses its daemons by default, this is the change that makes the output not being sent. I've added `org.gradle.daemon=false`  to my local gradle.properties-file ([like described in the docs](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon)) and it dropped me the error you got.

As this (again) is some problem with that daemon, I will have to take some time, finding a way to provide you with your information.

Bug confirmed.

**Comment by FibreFoX** [comment]
Hi @embee1981, thanks for reporting this, it is a problem with the daemon-handling. I have found a way for telling gradle to print stdout and stderr to the normal output, the output recieved by the gradle-daemon is covered/mangled and it needs special adjustment for getting all that to the user.

With gradle 3 the daemon is "used per-default", switching the personal setting (like mentioned in my answer before), does work, but disables the use of the daemon. I personally don't like that daemon, because it introduces another location for mistakes (especially when having buggy software which does not close threads or filehandles like in #12).

A fix will be provided soon.

**Comment by FibreFoX** [comment]
Good news:
I have uploaded a possibly fixed version, could you check with `8.5.3-SNAPSHOT`-version?
```groovy
buildscript {
    dependencies {
        classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: '8.5.3-SNAPSHOT'
    }
    repositories {
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}
```

**Comment by embee1981** [comment]
Heya, still no joy with the new snapshot. I can use the disable daemon workaround in the meantime though :-)

**Comment by FibreFoX** [comment]
@embee1981 what do you mean with "joy"?

The project you provided now does print the stdout and strerr when calling `gradlew jfxRun`.

```java
package com.test;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application{

    @Override
    public void start(Stage primaryStage) throws Exception {
        System.out.println("Printing to sys out");
        System.err.println("Printing to sys err");
        // throw new RuntimeException("Throwing a runtime exception, should see stack trace");
        System.exit(0);
    }

    public static void main(String... args) {
        launch(args);
    }
}
```

Running gradle now does this output for me:
```
C:\develop\tmp\JavaFxPluginDemo>gradlew jfxRun
Download https://oss.sonatype.org/content/repositories/snapshots/de/dynamicfiles/projects/gradle/plugins/javafx-gradle-plugin/8.5.3-SNAPSHOT/javafx-gradle-plugin-8.5.3-20160820.114916-1.pom
Download https://oss.sonatype.org/content/repositories/snapshots/de/dynamicfiles/projects/gradle/plugins/javafx-gradle-plugin/8.5.3-SNAPSHOT/javafx-gradle-plugin-8.5.3-20160820.114916-1.jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:jfxJar
:jfxRun
Running JavaFX Application

BUILD SUCCESSFUL

Total time: 11.568 secs
C:\develop\tmp\JavaFxPluginDemo>
```

What problems do you still have now, maybe I can help further to locate this bug?

**Comment by FibreFoX** [comment]
I'm starting to realize, that there is no output .... hm ... only when having a problem?! Very strange ... will work on it...

**Comment by FibreFoX** [comment]
@embee1981 can you recheck? I have uploaded a new SNAPSHOT-version :)

**Comment by embee1981** [comment]
Awesome :-) Its printing now to the console with daemon running, good job!
