### ISSUE TITLE
The dependOn list for the jfxJar task appears to be reset after it is configured

### ISSUE THREAD

**Issue by swpalmer** [FibreFoX/javafx-gradle-plugin#31]
I wanted to make sure that if obfuscation was enabled that it ran prior to the jfxJar task and set the alternativePathToJarFile appropriately.

However it doesn't work.

I have:

	if (file('src/main/proguard/configuration.pro').exists()) {
		println "ProGuard configuration file found.  Adding Obfuscate task."
		task obfuscate(type: proguard.gradle.ProGuardTask, dependsOn: jar) {
			mustRunAfter ('javadoc')
			injars  "${jar.archivePath}"
			libraryjars "$javaHome/lib/rt.jar"
			libraryjars "$javaHome/lib/jce.jar"
			libraryjars "$javaHome/lib/ext/jfxrt.jar"

			outjars "$buildDir/proguard/${jar.archiveName}"
			printseeds "$buildDir/proguard/proguard_seeds.txt"
			printmapping "$buildDir/proguard/proguard_map.txt"

			configuration 'src/main/proguard/configuration.pro'
		}
		jfxJar.dependsOn obfuscate
		jfx.alternativePathToJarFile = "$buildDir/proguard/${jar.archiveName}".toString()
	}
	println "jfxJar depends on ${jfxJar.dependsOn}"

The print of jfxJar.dependOn shows the dependency on the obfuscate task.  However if I print the same thing here:

	gradle.taskGraph.whenReady { graph ->
	    println "jfxJar depends on ${jfxJar.dependsOn}"
	}

the obfuscate dependency is gone.

Note that even if I force obfuscate to run I see jfxJar still prints: "Could not find specified alternative JAR-file" even though the jar is clearly at the correct path.

**Comment by FibreFoX** [comment]
Hi @swpalmer, can you provide some small project where I can reproduce this?

**Comment by FibreFoX** [comment]
Hi @swpalmer, I think I broke this for implementing my daemon-mode workaround by changing the way the tasks are registered, I can reproduce this wrong behaviour with my own dummy-project.

**Comment by FibreFoX** [comment]
For documentation purpose: this is the block, which broke it: https://github.com/FibreFoX/javafx-gradle-plugin/blob/d693922918d1f653b226319f7b405c6eb854ed0c/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/JavaFXGradlePlugin.java#L62

I needed to introduce this way, for having the configured settings regarding NOT to patch the `ant-jfx.jar` ... the changes for having `alternativePathToJarFile` to work were done before this.

My work to do now: find a better way to handle this or just copy the dependsOn and other stuff (the later one is currently my prefered way).

**Comment by FibreFoX** [comment]
**Quickfix:** move your stuff after project-evaluation

```groovy
project.afterEvaluate {
if (file('src/main/proguard/configuration.pro').exists()) {
    println "ProGuard configuration file found.  Adding Obfuscate task."
    task obfuscate(type: proguard.gradle.ProGuardTask, dependsOn: jar) {
        mustRunAfter ('javadoc')
        injars  "${jar.archivePath}"
        libraryjars "$javaHome/lib/rt.jar"
        libraryjars "$javaHome/lib/jce.jar"
        libraryjars "$javaHome/lib/ext/jfxrt.jar"

        outjars "$buildDir/proguard/${jar.archiveName}"
        printseeds "$buildDir/proguard/proguard_seeds.txt"
        printmapping "$buildDir/proguard/proguard_map.txt"

        configuration 'src/main/proguard/configuration.pro'
    }
    jfxJar.dependsOn obfuscate
    jfx.alternativePathToJarFile = "$buildDir/proguard/${jar.archiveName}".toString()
}
println "jfxJar depends on ${jfxJar.dependsOn}"
}
```

**Comment by FibreFoX** [comment]
@swpalmer Can you check if `8.6.1-SNAPSHOT` works for you?

**Comment by FibreFoX** [comment]
I have updated the snapshot, can you please check, if everything now works as expected?

**Comment by swpalmer** [comment]
8.6.1-SNAPSHOT doesn't appear to be available using mavenCentral()

**Comment by FibreFoX** [comment]
@swpalmer please take a look at the README.md-file for getting SNAPSHOT-versions by providing Sonatype as snapshot-maven-repository

**Comment by swpalmer** [comment]
The dependsOn information is now correct with the snapshot.  The alternativePathToJarFile does not work though.

**Comment by FibreFoX** [comment]
As this is working now, issue will be closed. The problem with "alternativePathToJarFile" is already in a different issue.
