### ISSUE TITLE
How to add a splash screen to the bundled launcher?

### ISSUE THREAD

**Issue by slajar** [FibreFoX/javafx-gradle-plugin#35]
What I mean is a splash that is loaded before jre is started. After that I am on my own ;)

**Comment by FibreFoX** [comment]
You mean something like this?
https://docs.oracle.com/javafx/2/deployment/preloaders.htm
https://docs.oracle.com/javase/8/javafx/api/javafx/application/Preloader.html
https://blog.codecentric.de/en/2015/09/javafx-how-to-easily-implement-application-preloader-2/

**Comment by slajar** [comment]
No excaty. A preloader is code that is running. A splashscreen is just a simple image that is fired up before the actual application launches. I have used a combination of very early Splash and replacing it by an interactive splash as far as possible in the past.

Generally launchers provide a feature for this (see Launch4J or WinRun4J)

Java itself does provide a feature for this on the command line and I tried:
runJavaParameter = "-splash:start_splash.png"

runParameter doesn't show up in the cfg file :/
Do you have any idea why?

**Comment by FibreFoX** [comment]
Preloaders are often "misused" as smart splash screens ;) as they can have some loading status (which an image just can't).

`runJavaParameter` is only ment for the `jfxRun`-task, so your bundled executable needs a different setting for this (haven't tried it yet):
```groovy
jfx{
    // other stuff
    additionalApplicationFiles = 'src/main/subfolder-with-the-slash-image-in-it' // contains start_splash.png
    jvmArgs = [
        '-splash:start_splash.png'
    ]
}
```

**Comment by slajar** [comment]
Okay, I see. I tried:
```
additionalApplicationFiles = "src/main/splash/" // contains start_splash.png
  jvmArgs = [
          "-splash:start_splash.png"
  ]
```

and I got the error:

> * What went wrong:
A problem occurred evaluating root project 'AppInstaller'.
> No such property: additionalApplicationFiles for class: de.dynamicfiles.projects.gradle.plugins.javafx.JavaFXGradlePluginExtension_Decorated

**Comment by FibreFoX** [comment]
@slajar woops :D the property was `additionalAppResources`, sorry

**Comment by slajar** [comment]
Thanks that works like a charme!

**Comment by slajar** [comment]
Damn, it doesn't work on windows, while it is working on MacOSX.

The splash is placed correctly in the app folder and in the cfg file I find -splash:splash_start.png in the jvmArgs but the executable doesn't seem to use it.

Any idea?

**Comment by FibreFoX** [comment]
Thats strange, the documentation is stating to have that option:
http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html

> -splash:imgname
    Shows the splash screen with the image specified by imgname. For example, to show the splash.gif file from the images directory when starting your application, use the following option:
    -splash:images/splash.gif

As I'm developing on windows, could you provide me a simple stripped down project? Maybe the JVM is faster on windows ;) and just does not show it for very long.

**Comment by slajar** [comment]
Thanks, I could provide you with a small project afterwards.

Anyway, first theoretically. 
When I start up java.exe -splash:splash_start.png ... java shows up the Splash correctly.

The cfg file has this 
```
[JVMOptions]
-splash:splash_start.png
```

It seems to to be ignored on Windows. Can I test it some how that is is used?

**Comment by FibreFoX** [comment]
Just to make sure: did you check this on mac- and linux-systems with success? Some example-project would be good, because I don't have the time to create all the projects when an issue arrives ;)

**Comment by slajar** [comment]
Ohh, I think I just found the reason why it does not work. The launcher doesn't use java.exe and loads jvm.dll by JNI. The splash feature is unfortunately implemented in the java.exe ... I am lost here, until the created launcher supports a splash-screen feature.

**Comment by FibreFoX** [comment]
Thats right, but no JNI ;) it directly loads the JVM.

I've found an open issue on the openJDK-project related to this: https://bugs.openjdk.java.net/browse/JDK-8087431

**Comment by FibreFoX** [comment]
@slajar maybe you really should switch to not using real spash-screen, but more short living stages, like I did inside my CDI-example: https://gist.github.com/FibreFoX/294012b16fa10519674b

**Comment by FibreFoX** [comment]
@slajar are you okay with this issue getting closed as the JDK (especially the native launchers) are not capable of "real" splash screens?

**Comment by FibreFoX** [comment]
Another good gist: https://gist.github.com/jewelsea/2305098

**Comment by slajar** [comment]
The main problem of using a later Splash is that starting the JRE from a CDROM drive takes more than 2 minutes. That's why I need a very early splash... I'll probably do it on my own.
Thanks anyway.

**Comment by FibreFoX** [comment]
So you are generating no real installer, to make it possible to start your application like a live-system?

What about a self-made wrapper for your CD? Very long time ago (where I used CD-ROMs :D) this was worked around by some fancy looking start-menu. Maybe you can create some "copy to temp-folder, then start the app"-application which gets called (would increase speed).
