### ISSUE TITLE
make it possible to provide absolute paths

### ISSUE THREAD

**Issue by swpalmer** [FibreFoX/javafx-gradle-plugin#36]
This makes it awkward because "$buildDir" and other properties expand to the absolute path.

e.g.

    jfx.alternativePathToJarFile = "$buildDir/proguard/${jar.archiveName}".toString()

does not work, but 

    jfx.alternativePathToJarFile = "build/proguard/${jar.archiveName}".toString()

does.

**Comment by FibreFoX** [comment]
You are right, this setting is "project-folder relative", so this less a but for me ;) nevertheless I will take a look into this.

**Comment by FibreFoX** [comment]
As this counts for other paths too, this is a more "global" problem of the current design. I will tinker a bit to provide a nice solution when publishing `8.6.1` including your `dependsOn`-fix

**Comment by FibreFoX** [comment]
This is available as `8.7.0-SNAPSHOT`, will be published when having implemented something to fix #38

**Comment by FibreFoX** [comment]
This will now be available in `8.7.0` (when it hits maven-central), please activate this by adjusting your configuration:
```groovy
jfx {
    // ...
    checkForAbsolutePaths = true
}
```

**Comment by swpalmer** [comment]
Why the need for checkForAbsolutePaths ?  Is there really a case where absolute paths were correctly being interpreted in a relative way?   I can't imagine there are many cases where leading slashes are provided in the path by accident, and it would be always wrong if there was a Windows drive letter stuck in the middle :-)

**Comment by FibreFoX** [comment]
This is just for maintaining the same behavior, I'm planing to change this in some of the next releases ;)
