### ISSUE TITLE
Plugin version number in examples uses a potentially conflicting name

### ISSUE THREAD

**Issue by toolforger** [FibreFoX/javafx-gradle-plugin#40]
The examples use a substitution variable for the plugin version number, which is established best practice for multi-project configurations.
However, the name `gradle.currentPluginVersion` may collide with usage for other plugins; such collisions should be avoided by renaming the variable to something derived from the plugin name, e.g. `javafx.gradle.plugin.version`.

Note: I'm leaving out the `current` bit because that variable could be set to any version number - from the perspective of the `build.gradle` file, it's "the version of the plugin I am supposed to use, whichever that is".

**Comment by FibreFoX** [comment]
As all example-projects are using a file from outside the example-structure, you have to adjust your configuration anyways.

I can't see any bug here, why do you think this is a bug?

**Comment by toolforger** [comment]
Examples are there to show "how it's done".
So people may think that `gradle.currentPluginVersion` is a good variable name for their projects, which it isn't - in that context, "current" would actually be wrong.

I.e. I'm proposing to write examples from the perspective of "how should this look like in the application coders' projects", instead of "how do we factor out commonalities of all these example projects".
Even if the latter was the original motivation for having the variable in the first place :-)

**Comment by FibreFoX** [comment]
The main idea of the example-projects is to show the configuration-part (`jfx`) and the file-structure, not the buildscript-part. I never said that my variable-naming is good, **but I will think about a nicer name**. It was a fight to get this thing into the `buildscript`-block ;) so I was happy to have it there

Taking the example-projects does not take the responsability from the developer to think about the own written code, so as I'm not showing some "best practise", this should be clear to every developer.

**Comment by FibreFoX** [comment]
Does `latestJavafxGradlePluginVersion` sound good enough? ;)

**Comment by toolforger** [comment]
I'd leave "latest" out: If people follow the structure with a version variable, they will usually want to stay with a specific version of the plugin so they can be confident about build stability.
I'd suggest `javafxGradlePluginVersion` sounds fine to me.
The alternative I considered was `javafxGradlePlugin.version`, but I think that's giving the wrong signal: the namespace for this kind of variable is managed in the project, not in the plugin, and `javafxGradlePlugin.version` would look as if the plugin were assuming a specific namespace.

**Comment by FibreFoX** [comment]
As the buildscript-block is very special (not being ext-aware: https://issues.gradle.org/browse/GRADLE-2413), I will change it to `javafxGradlePluginVersion`
