### ISSUE TITLE
(Improvement) Add a warning that .deb packaging can be slow

### ISSUE THREAD

**Issue by toolforger** [FibreFoX/javafx-gradle-plugin#41]
I'm seeing extremely slow `dpkg-deb` builds here. Thought something was broken.
Turns out this is because `dpkg-deb` does frequent disk syncs, trading speed for safety; ironically, this tends to get worse with newer file systems (ext4 and btrfs are particularly notable for this behaviour).
Here's a data point: On my SSD-equipped, plenty-of-RAM developer machine, building both .deb and .rpm reports 8 mins 3.162 secs, of which .deb took the majority.

The best that `javafx-gradle-plugin` can do is to mention this potential problem in the docs where discussing packaging options.

More background information can be found at https://wiki.debian.org/Teams/Dpkg/FAQ#Q:_Why_is_dpkg_so_slow_when_using_new_filesystems_such_as_btrfs_or_ext4.3F

**Comment by FibreFoX** [comment]
This is indeed something to mention ;) but I would prefer the official documentation of oracle doing this, as this ist just a wrapper. Detecting the setup where this is the case might be near to impossible. As this is a inconvenience of the `javapacker` ... or the `dpkg-deb`-tool, i don't really feel responsible for this.

**Comment by FibreFoX** [comment]
Despite of this gradle-plugin not being responsible, I might have found a way to detect the scenario for some warning.

**Comment by toolforger** [comment]
Ah, I was thinking about adding a line in the docs.
This should work, too, it's just a different set of pros and cons.

**Comment by FibreFoX** [comment]
🍰 documentations are subject of being skipped too often ;) so detecting the scenario and showing this to the developer (every time they are using this) might be a more proper solution.

Thanks for pointing this out, makes me feel like this gradle-plugin really gets used :D

**Comment by toolforger** [comment]
Well, I'm probably not going to be a user. Trying to remote-control one complex tool through another one always carries additional risks; given that the tool being remote-controlled is the Oracle JFX bundler which is trying to be too many things and not being very good at being any of them.
