### ISSUE TITLE
create more JNLP-examples

### ISSUE THREAD

**Issue by FibreFoX** [FibreFoX/javafx-gradle-plugin#44]
Most users are too confused when it comes to JNLP-bundler, so things like signing and `jnlp.outfile` are often unknown. To solve this, more examples are needed

**Comment by JustGregory** [comment]
Well, both more examples *AND* documentation. For any project I'm watching, I look for good docs to know what the heck I'm doing.

What makes good docs? I have a personal ideology when it comes to software docs (in general) that I'd like to share. I know, not every developer wants to write documentation; but at some point it's trading the time to explain things really significantly well, or having users end up asking the same questions if they cannot find the answers.

My design philosophy (for docs in general, and Gradle/groovy scripting in moderation, and JavaFX+Gradle in THIS particular case) is that I want to look at them from two primary diametrically-opposing views, as well as ancillary docs that bring it together.
 1. From a bottom-up, "this build script line does THIS" functionality. This is where a dev can look when comparing example/tutorial build scripts and know what each line, each parameter, will be doing. Great for the first-time/inexperienced developer who is trying to understand a particular line of code or script.
 2. From a top-down, "I want to have [feature] so I add THIS block of lines". This is where a dev can look when going beyond an initial build script and customize and build a better project script. Great for slight to moderately-experienced devs who want to understand HOW to use the above lines together.
 3. From an all-around, "I need to see broad tutorials and examples of this" viewpoint. This is for many struggling first-time as well as moderately-experienced devs who need a more holistic "conversational" style of documentation around both starting build scripts as well as more feature-complete examples that can be used.

Well, all that may be overstating it in places; but I'm often reminded of how different people will learn from different manners of viewing things. Not every developer would look at Oracle Docs and "know" how to code a Java class the very first time; some people understand on the first read-through, some understand only after seeing a bunch of charts, graphs, diagrams, and assorted visual stimuli. I'm somewhat towards the latter of the midway point than the former, so I can definitely feel the appeal of visually-appealing docs, but I also appreciate a good amount of technical documentation, when it's fully descriptive and essentially "feature complete", and so I'm often capable of picking out the finer points of a selection of paragraphs.

I guess what I wanted to end up saying in my second paragraph, is that we developers are close enough to our own projects, that we "know what we know" about its features, its issues, that often we forget to document for the next guy (or gal, being gender-inclusive). Different people learn at different rates and even ask or don't ask what they need to know in various ways. I know in my own personal development cycle, I'm working hard at documentation, so I thought I'd add in my two cents (or euro, or kroner, or whatever ;P )...

**Comment by FibreFoX** [comment]
Hi @JustGregory , I will take all these points for my next vacation, where I planned to rework my personal website and (now the important part) to create some documentation-websites for this plugin and the maven-equivalent. As this is only getting some time from my free spare time, I am happy to have this plugin where it stands today, debugging all this stuff is really exhausting, because this technology is not used by my company, makes it even more hard to develop these things.

Yes, a lot of people don't read the oracle-docs, which IMHO annoys me a lot, because developers can't just "oh hey, I have found the missing peace between two technologies" and think they only stay at that found tool without reading a bit about the other part of technologie they are using (especially when it's stated on the main page ... "is a convenient-wrapper"). Some first aid to this documentation-wound is to use the SEARCH (which is really not used a lot ... at least it feels like this), or to look at the existing example-projects.

That configuration-website for the javafx-maven-plugin was just some experiment to get in touch with polymer, next websites (means the javafx-maven-plugin and javafx-gradle-plugin will have their own ones, maybe with some shared core-javascript) will be written with [Vue](https://github.com/vuejs/vue/) which should work out better. I can hear you saying "but thats no documentation!!!111", and you know what, you are right ;) that will be the lazy "I have to write a lot of stuff"-part AFTER these "I click on buttons to get some configuration"-work being done. There was a lot to learn while developing and debugging, or writing nasty workarounds (... I had to use ASM ...), but the technology JavaFX itself is somewhat mostly unused by me, and I'm very unhappy about this situation.

You should ask yourself "what can I do to help in this situation", and besides of reporting found bugs, or even prepare pull-requests, you might want to start writing some blog-article where you can share first-hands-experiences with this plugin. I bet there is a lot of stuff, which is totally confusing or just not nice enough for you while using this plugin, but this does not have to stay inside your head.

It might sound harsh, but I want to thank you for your two .... coins? :D

**Comment by JustGregory** [comment]
You and I have the same annoyance at other people who don't read the docs, Oracle's or otherwise; and you can believe I fully understand your sentiments. (Well, except I hadn'd heard of Vue, and I hadn't really understood what it took in ASM for you to get started....)

It's okay, I didn't take any of that as "harsh"; maybe just a well-timed chance of you to vent some built-up frustration. Um, maybe I feel a little bit embarrassed on your behalf, or relieved on mine, that I had thought you perceived my words as a bit "preachy" or "pushy" where I only wanted to add a voice of encouragement and conversation.

... And now it's *my* turn to feel the embarrassment of my own accord; your request that I start writing a blog or article of my experiences with the plugin reminded me, I've been away from developing JavaFX for a time. I mean, *REALLY developing with it, not just *tinkering*. -- All I can really say is, after my father's auto accident and surgery in the last year, I've been somewhat shaken from getting into the kind of hard-core JavaFX - FXML - UI development that drew me to it. Lately, I've been more or less "treading water" in going over and over old projects, and it sucks, big time. And, I'm sorry that I haven't been more on the ball, with the FX parts of Java development like I would like, that I cannot give the kind of feedback as I -- and you -- would like to see.

**Comment by FibreFoX** [comment]
Point is taken :) I do know how frustrating the situation is, you aren't the only ones who are annoyed about no-documentation, its me too, because I need to answer all the questions here on github, stackoverflow or direct mail contact. Please don't feel embarrassment, I am thinking of it as some kind of "cheering up" for this being a good tool and to not let it take dust just because of missing documentation.

If you do have some questions which you just don't want to make an issue here, just send me some email, normally I do respond in 48 hours-timeframes.

That "harsh" part was added, because sometimes people misunderstood my intentions, because this is only written text, without emotions, all I want to say is "even if I sound mad or arrogant (or whatever), just don't take it personally, it's just the moody side of me ... probably having too few spare-time, or too insufficient sleep". I wish you all the best with your "tinkering" ;) I haven't forgotten, that you are developing some RPG-maker-thing.

But to bring this back to topic: JNLP-examples will be added before the new configuration-websites and before the documentation is done, just because a lot of people here are looking for code, and having some example-project makes it better to link them to.

**Comment by FibreFoX** [comment]
As JNLP for newer JDK-version gots removed from its core, I will close this as part of the rework. (But chances are there that JNLP for JDK8 will get added later)
