### ISSUE TITLE
Dagger2

### ISSUE THREAD

**Issue by Hospes** [FibreFoX/javafx-gradle-plugin#48]
Hi Guys!

I'm trying to include dagger2 into my application.
I add "apt" plugin and dependencies on dagger
```
    compile 'com.google.dagger:dagger:2.8'
    apt 'com.google.dagger:dagger-compiler:2.8'
```

when I run task "gradle clean build"
I see generated classes from dagger, but I can't access them from my classes.
Can someone tell me if it's javafx-plugin issue or mine?
I mean when I'm execute Sync Gradle project, then Idea add build folder as "excluded" from application module. Maybe this is the issue why I can't access generated classes ?

**Comment by Hospes** [comment]
Sorry guys, I found solution.
Just have to set sourceSet:
```
sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', 'build/generated/source/apt']
        }
    }
}
```

**Comment by joyerf** [comment]
How to add "apt" plugin
Could not find method apt() for arguments [com.google.dagger:dagger-compiler:2.22] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
