### ISSUE TITLE
adjusted-launcher-icon example: path name inconsistency

### ISSUE THREAD

**Issue by ChrisLMerrill** [FibreFoX/javafx-gradle-plugin#49]
In the readme, it says:
...into the folder src/main/deploy/windows for the bundler....

but in the example, the file is in
  /src/main/deploy/package/windows

For me, the readme is correct and the example did not work.

**Comment by ChrisLMerrill** [comment]
Oops - sorry it was the other way around. Example works...readme was wrong.    :)

**Comment by FibreFoX** [comment]
Hi there, thanks for pointing that out :) I'm used to forget that "package"-part, thats my fault, sorry.
