### ISSUE TITLE
Executable for Windows 10

### ISSUE THREAD

**Issue by ultrasites** [FibreFoX/javafx-gradle-plugin#50]
Hello,

my native App works on Win7 and in my IDE on Win10, but not as bundled App on Win10.

The Error occurs by including the JSSC Lib:
https://github.com/scream3r/java-simple-serial-connector

Can you help me?

Thank you!

**Comment by FibreFoX** [comment]
Hi there,

what errors do occur? While creating the native bundle? I need more information first, maybe a small project where I can recreate your problem (maybe it's just a problem of 32bit/64bit?).

**Comment by FibreFoX** [comment]
@ultrasites Please come back with more input, I will close this issue meanwhile
