### ISSUE TITLE
How to include JRE with linux deb executable

### ISSUE THREAD

**Issue by DastanIqbal** [FibreFoX/javafx-gradle-plugin#53]
I am using openJDK+openJFX. I stuck on deployment, without jre my app is not working. I want to add JRE in app. I know its not recommended. but I want to add in my package.

Thanks

**Comment by FibreFoX** [comment]
Hi @DastanIqbal, thanks for using this gradle-plugin ;)

Just some questions:
- Why is your app not working? What is the behaviour of your installed app?
- Could you provide the jfx-part of your gradle-buildscript?

**Comment by DastanIqbal** [comment]
Thanks FibreFox, actualy I was talking about the deb file, when I am installing with dpkg -i app.deb file,Its successfully installed but when I was trying to run, on that time its was throwing error JVM_onCreate something, may be my app was not able to find JRE. so I was trying with embed JRE with executable(.deb)

I just solved with 
bundleArguments = [
            // dont bundle JRE (not recommended, but increases build-size/-speed)
            runtime: '/usr/lib/jvm/java-8-openjdk-amd64/jre/'
    ]

Thanks

**Comment by FibreFoX** [comment]
So if you want include the runtime, did you try to just remove that "runtime"-line completely? ;) The "runtime: null"-parameter is an internal trick to NOT INCLUDE the JRE, if you just remove that whole line, it defaults to INCLUDE the JRE.

BUT: If you DO NOT WANT to include the JRE, but having your application being able to use the installed java(fx), you are required to adjust the dep-installer-script. Have a look at https://github.com/VocabHunter/VocabHunter/pull/17/files

**Comment by FibreFoX** [comment]
@DastanIqbal does this answer your questions? If so, this now can be closed ;)

**Comment by DastanIqbal** [comment]
Ya VocabHunters looks good. :)
