### ISSUE TITLE
Question: Description for exe file

### ISSUE THREAD

**Issue by ronisaha** [FibreFoX/javafx-gradle-plugin#54]
Is there a config property to set the Description for the exe. By default its using the {appName}.exe

I want to set description for my application(Like: My Cool App).

![image](https://cloud.githubusercontent.com/assets/1433652/22579293/19554166-e9f9-11e6-871a-cbcd9a4e1a28.png)

**Comment by FibreFoX** [comment]
Will check it. Do you know if the (ugly ant-style) `javapackager` has some flag for this?

**Comment by FibreFoX** [comment]
Hi there, this is nothing inside the exe-file. If you rename your exe-file, it will change the description too ;)

The only parts, which can be overridden, are the same as the original `javapackager` is able. Some parts are only for the installers, you can find a list here: https://github.com/teamfx/openjfx-8u-dev-rt/tree/fd634925571310284b02d89ff512552e795ba5e8/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/bundlers/BundleParams.java

Please make sure to change these inside the bundleArguments-block, something like this:
```xml
<configuration>
    <!-- other stuff -->
    <bundleArguments>
        <copyright>myCopyright</copyright>
    </bundleArguments>
</configuration>
```
