### ISSUE TITLE
launcherArguments for secondaryLaunchers

### ISSUE THREAD

**Issue by vhkrausser** [FibreFoX/javafx-gradle-plugin#55]
If we specify a secundary launcher for the build with custom lauch parameters, all lauchers have the parameters from the latest configuration readed by the plugin.

This happens (I belive ) at line `212` of the `JfxNativeWorker`. 

Where we read `params.put(StandardBundlerParam.ARGUMENTS.getID(), new ArrayList<>(arguments));`

Should be:   `secondaryLauncherGenerationMap.put(StandardBundlerParam.ARGUMENTS.getID(), new ArrayList<>(arguments));`

**Comment by FibreFoX** [comment]
Indeed, thanks for catching this 👍

**Comment by FibreFoX** [comment]
This is now fixed :) should take a bit to hit maven-central
