### ISSUE TITLE
How to sign the jar/bundle

### ISSUE THREAD

**Issue by chris-scorpio** [FibreFoX/javafx-gradle-plugin#56]
Firstly, thanks for all the hard work you've put into this plugin.

Have been trying to figure out how to get the jar/mac bundle to be signed using an existing keystore. The corresponding command in javapackager would be -signjar. Looking at the code I can see that JNLP jars are signed and that a keystore can be created but can't see anything for normal jars/bundles.

Looks like the signing for windows bundles is separate from javapackager.

Can you point me in the right direction please.

**Comment by FibreFoX** [comment]
```groovy
jfx{
    // ...
    noBlobSigning = false // when using bundler "jnlp", you can choose to NOT use blob signing
}
```

You might want to set `noBlobSigning = true` switches to use normal "jarsigner" when calling jfxNative. The corresponding `javapackager`-equivalent does NOT sign the jar-files like expected, because it uses the so-called BLOB-signing, which never get grip in the java-ecosystem (and it will be dropped with JDK9 anyway), therefor I have manually added that feature using the normal jarsigner-process.

Does this help you?

**Comment by FibreFoX** [comment]
Oh wait a minute ... thats not  true ... sorry, will check for it ;)

**Comment by FibreFoX** [comment]
@chris-scorpio Hi there, sorry for the confusion on the answers before.

You are right, the signing-process is only applied for JNLP-files when using this plugin, but it is not the signing that you want! The javapackager introduced a method called `BLOB Signing`, which gets removed from the JDK9 (it never got grip in the ecosystem, nor tool-support to check the signature!!), this means that the `corresponding command` is not what you are expecting.

Just a stupid question: what is your use-case for having signed jar-files, when you are required to have the native launcher being signed on Mac?

Having your jars being signed can get archieved by using the normal `signing`-plugin provided by gradle itself:
https://docs.gradle.org/current/userguide/signing_plugin.html

There is no built-in step for signing jars using the jfxJar-Task .... and I'm starting to think about it ;)

**Comment by chris-scorpio** [comment]
Thanks for the responses.

The company I work for is requesting that the win/mac/linux app/installers are signed so have spent the last couple of days looking into various methods, just assumed that the jars themselves also needed signing [will look into the gradle signing plugin for this].

**Comment by FibreFoX** [comment]
Oh, if it is only about the installers, you are not looking for signing the JAR, but the EXE/MSI/DEB/RPM-installers/native launchers? Don't know about your requirements, but are you sure you want to sign the JARs and not the native launchers/installers?

**Comment by FibreFoX** [comment]
Just some of my thoughts:

* What is the idea of having SIGNED JARs when having native launchers? As far as I can tell, there is no benefit, as the native launcher loads the (bundled or locally installed) JRE via native library loading and runs your JAR-files normally. No technical benefit
* What is the idea of having SIGNED NATIVE LAUNCHERS? This is reasonable on high-security systems, or when having special native launchers (own compiled ones with special content or something like that). Please keep in mind that the JRE contains unsigned jars and a lot of binaries, where unsigned libraries could be included, you have to ensure for all being signed ;) and checking them on windows, they are signed with SHA-1, which seems to getting ugly (http://shattered.io/)
* What is the idea of having SIGNED INSTALLERS? High-security systems (there might be different understandings about the term "high-sec system" like I am using) might be configured to refuse unsigned installers (but they should refuse installers anyway!), they "just" try to ensure that the content wasn't messed with.

;D maybe you could try to describe what you really need

**Comment by FibreFoX** [comment]
One additional observation: the `packager.dll`-file is UNSIGNED, this is the first library loaded by the native launcher (I don't care for the runtime-`msvc*.dll`-files) ... this might be worthy to be reported as a bug on the oracle-bugtracker. This means: this is a file where some "strange mutation" could happen to "break" your signed native launcher ... in the case you aren't signing stuff that is not yours.

**Comment by chris-scorpio** [comment]
Hmm, some sound reasoning, I guess my need is for just the launcher [e.g.  .app to keep mac gatekeeper happy] and the installers [e.g. to prevent windows pop-up to show it's not verified] to be signed.

So I guess the question is, does the wrapper plugin allow me to sign the mac installer [due to the phrasing of the -nosign in the deploy command] or do I need to find other ways to achieve this?

Windows looks like I would definitely have to use other means [e.g. inno setup with a sign tool]

Thanks for your patience and guidance on this matter, am new to the signing/security side of applications.

**Comment by chris-scorpio** [comment]
Thanks for info, the bundle arguments helped me out alot along with reading up loads on certificates etc.

**Comment by FibreFoX** [comment]
Does that mean this issue can be closed?

**Comment by chris-scorpio** [comment]
Yes it can be closed, but one last question - where did you see the parameter for signBundle as couldn't see it in the javapackager arguments section?

**Comment by FibreFoX** [comment]
The `javapackager` is the tool from the JDK, which accesses the internal libs, but the javafx-gradle-plugin accesses that API directly, like the `javapackger` does, which means that all CLI-parameters are not mapped one-to-one.

For finding all arguments, I have to look at the sourcecode of the bundlers. Some arguments are normal parameters, mosty ones which are often-used ones, and the others have to be provided via that special `bundleArguments`-property. There are 4 types of special bundlers, and one "PackagerLib" (which is responsible for creating that jfx-jar). [You can look at the sourcecode where each type of bundler](https://github.com/teamfx/openjfx-8u-dev-rt/tree/master/modules/fxpackager/src/main/java/com/oracle/tools/packager), sometimes it is hard to find them, because of inheritance.

**Comment by bwRavencl** [comment]
@FibreFoX first of all excuse me for summoning this already closed issue, but I have a question regarding your following statement, and maybe you can help me out here.

> What is the idea of having SIGNED JARs when having native launchers? As far as I can tell, there is no benefit, as the native launcher loads the (bundled or locally installed) JRE via native library loading and runs your JAR-files normally. No technical benefit

I'm currently in the process of getting familiar with deploying Java apps as self contained applications, i.e. shipping a client application as an MSI with a self contained JVM.
How can I assure that nobody is tampering with the jar files that are shipped with the native launcher?
Shouldn't there be a way for the native launcher to verify a potential signature of the jars included in the application?
I just did a quick test and replaced the jar file of my app with a modified one, containing some extra (potentially malicious) piece of code and the launcher ran it without complaining.
Is there really no standard way to prevent this by signing the jars or "bind" the executable in any way to the jars it has been delivered with?
