### ISSUE TITLE
Failed to create .exe with dependencies jar

### ISSUE THREAD

**Issue by marckaraujo** [FibreFoX/javafx-gradle-plugin#58]
I got this error for every dependency jar in my project when I run jfxNative:

The jar lib/xxx.jar has a main class com.xxxx that does not match the declared main xxxx.MyMainApp

But it creates the .exe file.
When I try to run, this show a box window with "Error invoking method"

Then: "Failed to launch JVM" and it finish.

JAVA_HOME is jdk1.8.0_121
Windows 7 64 Bits

```
jfx {
    // minimal requirement for jfxJar-task
    mainClass = 'com.math.pro.ak.MainApp'

    // minimal requirement for jfxNative-task
    vendor = 'ProAK'
    
    // gradle jfxJar
    css2bin = true
    updateExistingJar = true
}
```

**Comment by FibreFoX** [comment]
Does this fail when this is removed?
```
    css2bin = true
    updateExistingJar = true
```

**Comment by marckaraujo** [comment]
Yes, same error.

**Comment by FibreFoX** [comment]
When you get warnings about some "MainClass found but not the specified one"-entries, this is normal, its something from the underlaying `javapackager`

**Comment by FibreFoX** [comment]
Can you try to create some small reproducable example project for this?

**Comment by marckaraujo** [comment]
My project is really a big one, well I need to find a way how I can create a sample for you.

**Comment by marckaraujo** [comment]
That is something that could help before I try to create a sample?

**Comment by FibreFoX** [comment]
So your main problem is, that you get `Failed to launch JVM`, right? Have you tried to execute the generated jar-file inside build/jfx/app ?

**Comment by FibreFoX** [comment]
I really need to reproduce this, often it's some exception being thrown or some missing dependency. Do you use some bundled JRE, or are you removing the JRE via `bundleArguments`?

**Comment by marckaraujo** [comment]
I dont use any bundled JRE. Should I put this in build.gradle?

```
bundleArguments = [
        // dont bundle JRE (not recommended, but increases build-size/-speed)
        runtime: null
    ]
```

**Comment by FibreFoX** [comment]
You dont use the bundled JRE? Now I am confused.

Normal behaviour is that the javapackager generates some JRE inside the runtime-folder ... if you are removing this, you HAVE to set bundleArguments like you commented.

The `Why?` behind: there is some `.cfg`-file containing some entry about the runtime ... if it is empty, the exe tries to use some locally installed runtime. On Windows-Systems the JRE-detection uses some registry-entries.

**Comment by marckaraujo** [comment]
To be honest I dont know if I use bundled JRE, probably not if it isnt a default JavaFX Project Settings.

My .cfg is: 

```
[Application]
app.name=Pro-AK-1.0.0
app.mainjar=project-jfx.jar
app.version=1.0
app.preferences.id=com/math/pro/ak
app.mainclass=com/math/pro/ak/MainApp
app.classpath=lib/h2-1.4.193.jar;lib/jboss-logging-3.3.0.Final.jar;lib/geoip2-2.8.0.jar;lib/commons-logging-1.2.jar;lib/fx-gson-2.0.1.jar;lib/javassist-3.20.0-GA.jar;lib/httpclient-4.5.2.jar;lib/maxmind-db-1.2.1.jar;lib/classmate-1.3.0.jar;lib/dom4j-1.6.1.jar;lib/javax.json-1.0.4.jar;lib/nv-websocket-client-1.20.jar;lib/jboss-transaction-api_1.2_spec-1.0.1.Final.jar;lib/java-method-invocation-builder-1.2.jar;lib/jackson-databind-2.9.0.pr2-SNAPSHOT.jar;lib/java-method-invocation-builder-annotations-1.0.jar;lib/jandex-2.0.3.Final.jar;lib/retrofit-2.1.0.jar;lib/oshi-core-3.3.jar;lib/jackson-dataformat-cbor-2.6.6.jar;lib/controlsfx-8.40.12.jar;lib/aws-java-sdk-core-1.11.102.jar;lib/socket.io-client-0.8.3.jar;lib/c3p0-0.9.5.2.jar;lib/converter-gson-2.1.0.jar;lib/jmespath-java-1.11.102.jar;lib/guava-16.0.1.jar;lib/commons-codec-1.9.jar;lib/aws-java-sdk-s3-1.11.102.jar;lib/annotations-15.0.jar;lib/kairos-material-components-0.3.jar;lib/hibernate-commons-annotations-5.0.1.Final.jar;lib/json-simple-1.1.jar;lib/aws-java-sdk-dynamodb-1.11.102.jar;lib/slf4j-api-1.7.22.jar;lib/hibernate-c3p0-5.2.8.Final.jar;lib/mchange-commons-java-0.2.11.jar;lib/gamesparks-java-sdk-0.2.1-SNAPSHOT.jar;lib/commons-lang3-3.1.jar;lib/hibernate-core-5.2.8.Final.jar;lib/jackson-core-2.9.0.pr2-SNAPSHOT.jar;lib/okio-1.11.0.jar;lib/oshi-json-3.3.jar;lib/json-20090211.jar;lib/kairos-core-0.5.jar;lib/kairos-framework-0.5.jar;lib/okhttp-3.5.0.jar;lib/gson-2.8.0.jar;lib/hibernate-jpa-2.1-api-1.0.0.Final.jar;lib/engine.io-client-0.8.3.jar;lib/ion-java-1.0.2.jar;lib/aws-java-sdk-kms-1.11.102.jar;lib/jna-4.2.2.jar;lib/joda-time-2.8.1.jar;lib/jackson-annotations-2.9.0.pr1.jar;lib/javapoet-1.7.0.jar;lib/sikulixapi.jar;lib/jna-platform-4.2.2.jar;lib/antlr-2.7.7.jar;lib/httpcore-4.4.4.jar
app.runtime=
app.identifier=com.math.pro.ak

[JVMOptions]

[JVMUserOptions]

[ArgOptions]

```

**Comment by FibreFoX** [comment]
`app.runtime=` this means "use the locally installed JRE", that entry is created when having that bundleArgument ... but this REQUIRES the targeted windows-system to have the JRE installed correct.

If you remove all bundleArgument-entries regarding the runtime/JRE, you should get a package with some bundled JRE (which personally I would recommend), and creates some different entry inside that `.cfg`-file ... and makes sure to have some runtime available when executing your app.

**Comment by marckaraujo** [comment]
I just test a small project of this big one with all this dependencies and running with very few pages. And the .exe generated works well.

The .cfg file is:

```
[Application]
app.name=Pro-AK-1.0.0
app.mainjar=project-jfx.jar
app.version=1.0
app.preferences.id=com/math/pro/ak
app.mainclass=com/math/pro/ak/MainApp
app.classpath=lib/h2-1.4.193.jar;lib/jboss-logging-3.3.0.Final.jar;lib/geoip2-2.8.0.jar;lib/commons-logging-1.2.jar;lib/fx-gson-2.0.1.jar;lib/javassist-3.20.0-GA.jar;lib/httpclient-4.5.2.jar;lib/maxmind-db-1.2.1.jar;lib/classmate-1.3.0.jar;lib/dom4j-1.6.1.jar;lib/javax.json-1.0.4.jar;lib/nv-websocket-client-1.20.jar;lib/jboss-transaction-api_1.2_spec-1.0.1.Final.jar;lib/java-method-invocation-builder-1.2.jar;lib/jackson-databind-2.9.0.pr2-SNAPSHOT.jar;lib/java-method-invocation-builder-annotations-1.0.jar;lib/jandex-2.0.3.Final.jar;lib/retrofit-2.1.0.jar;lib/oshi-core-3.3.jar;lib/jackson-dataformat-cbor-2.6.6.jar;lib/controlsfx-8.40.12.jar;lib/aws-java-sdk-core-1.11.102.jar;lib/socket.io-client-0.8.3.jar;lib/c3p0-0.9.5.2.jar;lib/converter-gson-2.1.0.jar;lib/jmespath-java-1.11.102.jar;lib/guava-16.0.1.jar;lib/commons-codec-1.9.jar;lib/aws-java-sdk-s3-1.11.102.jar;lib/annotations-15.0.jar;lib/kairos-material-components-0.3.jar;lib/hibernate-commons-annotations-5.0.1.Final.jar;lib/json-simple-1.1.jar;lib/aws-java-sdk-dynamodb-1.11.102.jar;lib/slf4j-api-1.7.22.jar;lib/hibernate-c3p0-5.2.8.Final.jar;lib/mchange-commons-java-0.2.11.jar;lib/gamesparks-java-sdk-0.2.1-SNAPSHOT.jar;lib/commons-lang3-3.1.jar;lib/hibernate-core-5.2.8.Final.jar;lib/jackson-core-2.9.0.pr2-SNAPSHOT.jar;lib/okio-1.11.0.jar;lib/oshi-json-3.3.jar;lib/json-20090211.jar;lib/kairos-core-0.5.jar;lib/kairos-framework-0.5.jar;lib/okhttp-3.5.0.jar;lib/gson-2.8.0.jar;lib/hibernate-jpa-2.1-api-1.0.0.Final.jar;lib/engine.io-client-0.8.3.jar;lib/ion-java-1.0.2.jar;lib/aws-java-sdk-kms-1.11.102.jar;lib/jna-4.2.2.jar;lib/joda-time-2.8.1.jar;lib/jackson-annotations-2.9.0.pr1.jar;lib/javapoet-1.7.0.jar;lib/sikulixapi.jar;lib/jna-platform-4.2.2.jar;lib/antlr-2.7.7.jar;lib/httpcore-4.4.4.jar
app.runtime=
app.identifier=com.math.pro.ak

[JVMOptions]

[JVMUserOptions]

[ArgOptions]
```

**Comment by FibreFoX** [comment]
If your application works when having some small app, there is some different problem, maybe combined with some other dependency ... have you checked to run the generated jfx-jar via CLI?

**Comment by marckaraujo** [comment]
Running only the jar with jfxRun, just found a problem:

`java.io.FileNotFoundException: file:\D:\Users\marcus\Documents\Workspace\pro-ak\build\jfx\app\project-jfx.jar!\mmdb\GeoLite2-Country.mmdb`

I use this code:

```
String path = MainApp.class.getResource("/mmdb").getPath();
File database = new File(path + "/GeoLite2-Country.mmdb");
```

With the jar, this path is wrong. Do you know how to refer a resource file to works with the jar?

**Comment by FibreFoX** [comment]
Which means this is no problem with this gradle plugin :) at least one good thing for me.

Is this a read-only-database? Have you tried `ClassLoader.getSystemClassLoader().getResource("/mmdb").getPath();`?

**Comment by FibreFoX** [comment]
If this is some resource which is not required inside the jar-file, you might want to take a look at this example: https://github.com/FibreFoX/javafx-gradle-plugin/tree/master/examples/additional-application-files

**Comment by marckaraujo** [comment]
@FibreFoX thanks for the link with the example.

But how to refer the additional file inside application and make it work for Win/Linux/Mac?

**Comment by FibreFoX** [comment]
There might be some misunderstanding about how this whole concept works:

When you are packaging your application, the current java-project is generated as some jar-file, containing all the classes and other files. After this, your jar-file is "converted" into some javafx-jar (jfx-jar in short), which differs in some special MAINFEST-entries, and all dependencies are copied to `build/jfx/app`. If you have `copyAdditionalAppResourcesToJar = true`, the files from `additionalAppResources` are copied to the `build/jfx/app`-folder too.

When creating a native bundle (the native binaries, not the installers), the jfx-jar and all the other files (dependencies and possible `additionalAppResources` are copied into `build/jfx/native/{appName}`. Just try the example I linked in the previous comment, you might see where your files will land.

Separating your additional files from the jar-files makes it possible to have read-write databases/files as part of your application. When you are having that file INSIDE that jar-file, your other applications are required to get "inside" the jar-files, not all dependencies using `File` can handle with that specials URLs.

To reference the files, you might end up using something like this:
```java
Path currentRelativePath = Paths.get("");
String s = currentRelativePath.toAbsolutePath().toString();
System.out.println("Current relative path is: " + s);
```
