### ISSUE TITLE
JVMArgs not getting by getParameters()

### ISSUE THREAD

**Issue by marckaraujo** [FibreFoX/javafx-gradle-plugin#60]
I have my arguments set like:

   ` jvmArgs = ["-agentlib:TakipiAgent", "debug"]`

I am trying to get the args inside my MainApp.class:

```
@Override
    public void start(Stage stage) throws Exception {

        Parameters parameters = getParameters();
       
    }
```

But its always null.

I tried with jfxRun and jfxNative

**Comment by JustGregory** [comment]
And what does your ```getParameters()``` method look like?

**Comment by marckaraujo** [comment]
@JustGregory https://docs.oracle.com/javase/8/javafx/api/javafx/application/Application.html#getParameters--

**Comment by FibreFoX** [comment]
Since when are the JVM arguments accessible ? getParameters is not ment for this. If you want to have additional parameters, please look at `launcherArguments`, but please be aware of your other issue #59
