### ISSUE TITLE
Native bundle runtime x86 problem

### ISSUE THREAD

**Issue by benqs** [FibreFoX/javafx-gradle-plugin#62]
I'm having a problem with creating native bundle with specified x86 jre.

``` 
bundleArguments = [
           runtime: 'C:\\Program Files\\Java\\jdk1.8.0_40\\jre'
 ]
```
With this work like a charm, jfx/native is created with specified jre bundled.

``` 
bundleArguments = [
           runtime: 'C:\\Program Files (x86)\\Java\\jdk1.8.0_40\\jre'
 ]
```
But when I change to x86 jre jfx/native is not created and there are no logs that would tell why.
I tried with other jre versions with same result.

**Comment by FibreFoX** [comment]
Are you bundling on a 64bit system?

**Comment by benqs** [comment]
yes

**Comment by FibreFoX** [comment]
Thats one of the problems, you are required to create the bundle for 32bit on 32bit-build-system, as per documentation from oracle: https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#JSDPG586

> Package per target platform
> 
> Self-contained application packages are platform-specific and can only be produced for the same system on which you build. To deliver self-contained application packages on Windows, Linux, and OS X, you must build your project on all three platforms.

This was a problem I tried to debug some time ago for the javafx-maven-plugin: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/81

Corresponding JDK-bug: https://bugs.openjdk.java.net/browse/JDK-8091056 (which is closed as WONT FIX)

**Comment by benqs** [comment]
You're right. With changing gradle jvm to 32bit it was able to build 32bit native.

**Comment by marckaraujo** [comment]
@FibreFoX , the [SO Question](http://stackoverflow.com/questions/43860197/javafx-only-run-with-jdk) is related to this?

I just created the .exe file using: [exe4j](https://www.ej-technologies.com/download/exe4j/files) and it works with JRE 1.8 X86.

But using jfxNative, it wont work with JRE 1.8 X86, only with JRE 1.8 X64.

**Comment by FibreFoX** [comment]
@marckaraujo Please create a new issue and attach a project where I can reproduce this. Thanks
