### ISSUE TITLE
Log4j2 configuration file location problem

### ISSUE THREAD

**Issue by Hospes** [FibreFoX/javafx-gradle-plugin#63]
Hi there!
Sorry if this question is not related to your plugin, but I need help and can't find solution for it.

I'm trying to use log4j lib for logging. And as described in documentation we can configure Log4j Loggers via configuration file.
This is quote from documentation:

1. Log4j will inspect the "log4j.configurationFile" system property and, if set, will attempt to load the configuration using the ConfigurationFactory that matches the file extension.
2. If no system property is set the properties ConfigurationFactory will look for log4j2-test.properties in the classpath.
3. If no such file is found the YAML ConfigurationFactory will look for log4j2-test.yaml or log4j2-test.yml in the classpath.
4. If no such file is found the JSON ConfigurationFactory will look for log4j2-test.json or log4j2-test.jsn in the classpath.
5. If no such file is found the XML ConfigurationFactory will look for log4j2-test.xml in the classpath.
6. If a test file cannot be located the properties ConfigurationFactory will look for log4j2.properties on the classpath.
7. If a properties file cannot be located the YAML ConfigurationFactory will look for log4j2.yaml or log4j2.yml on the classpath.
8. If a YAML file cannot be located the JSON ConfigurationFactory will look for log4j2.json or log4j2.jsn on the classpath.
9. If a JSON file cannot be located the XML ConfigurationFactory will try to locate log4j2.xml on the classpath.
10. If no configuration file could be located the DefaultConfiguration will be used. This will cause logging output to go to the console.

So I'm trying next:
I placed log4j2.json file into resources folder and try to make build but got error.

> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

Also I tried to place it in 'classpath' in src/main/mainpackagefodler/ near Main.class
But in this case log4j2.json never packed into jar file.

Also I tried to put **jvmProperties** and **userJvmArgs**:
`jvmProperties = ['log4j.configurationFile': 'resources/log4j2.json']`

But still got the same error.

Can you help me figure out where should I place configuration file or maybe set some params with path to this file?

**Comment by FibreFoX** [comment]
Have you tried to put that configuration file into `src/main/resources/log4j2.json`? The java-plugin from gradle uses the same folder-conventions like maven is using:
`src/main/java/` -> your java-classes (your root-package)
`src/main/resources/` -> your non-java files (like your json-file)
`src/test/java/` -> your java-test-classes (your root-package)

**Comment by Hospes** [comment]
@FibreFoX Yes, I placed log4j2.json into resources folder
src/main/resources/log4j2.json

Also I checked jar file to be sure that this files are there and everything is fine but library dont see it.

**Comment by FibreFoX** [comment]
Have you added jackson to your dependencies? http://stackoverflow.com/a/28100528/1961102

```groovy
dependencies {
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.8.2'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.8.2'
    
    compile group:"com.fasterxml.jackson.core", name:"jackson-core", version:'2.4.2'
    compile group:"com.fasterxml.jackson.core", name:"jackson-databind", version:'2.4.2'
    compile group:"com.fasterxml.jackson.core", name:"jackson-annotations", version:'2.4.2'
}
```

Adding jackson worked for me.

**Comment by Hospes** [comment]
@FibreFoX Fantastic! Thanks!!!
Sorry for this thread not related to your plugin.
One more question regarding plugin, you tell somewhere that you will write some wiki/documentation, how is it going, do you have time for it? :)
