### ISSUE TITLE
JRE 1.8 32bits

### ISSUE THREAD

**Issue by marckaraujo** [FibreFoX/javafx-gradle-plugin#67]
When running with jfxNative in a Win 7 64 bits the .exe file dont find JRE 1.8 32 bits and throw an error.

[SO Question](http://stackoverflow.com/questions/43860197/javafx-only-run-with-jdk?noredirect=1#comment74756917_43860197)
[Test Project](https://github.com/marckaraujo/gamesparksJavaFX)

**Comment by FibreFoX** [comment]
The project you have linked, contains this:
```groovy

jfx {
    // minimal requirement for jfxJar-task
    mainClass = 'com.gamespark.test.main'

    // minimal requirement for jfxNative-task
    vendor = 'ProAK'
    
    bundleArguments = [
        // dont bundle JRE (not recommended, but increases build-size/-speed)
        runtime: null
    ]
}
```
You have to remove that `runtime: null`-part, because this will REMOVE the bundled JRE. Normal process is to include the JRE for a native bundle. 
Just to make sure, how are you creating the 32bit-version? Are you using a 64bit-version of the JDK while creating the 64bit bundle and a 32bit-version of the JDK while creating the 32bit bundle ?

**Comment by marckaraujo** [comment]
@FibreFoX , I do have sure that the target system have the JRE installed.

- I executed jfxNative while JDK 64bits is installed then I removed the JDK and installed JRE 32bits.  

Probably you gonna say that you need JDK 32bits to generate a 32bits bundle.
However, I did the same process with 'exe4j' and it works normally with JRE 32bits.

Another sugestion is to have a jfxNative32 and jfxNative64.

**Comment by FibreFoX** [comment]
"exe4j" does different things, they do bundle both architectures, not only one (as the JDK does). 

This was opened as some bug a long time ago, but got closed as "won't fix": https://bugs.openjdk.java.net/browse/JDK-8091056

As this gradle-plugin relies on the provided javapackager (and its bundled resources), there is nothing I can do about.

**Comment by FibreFoX** [comment]
@marckaraujo Does this mean I can close this issue?

**Comment by marckaraujo** [comment]
If I have both JDK 64 and 32 bits installed, that is a way to choose what architecture I want to generate?

A little help with another question, I will bundle the JRE with the project, how do I specify that?

```
bundleArguments = [
        // dont bundle JRE (not recommended, but increases build-size/-speed)
        runtime: null
    ]
```

**Comment by FibreFoX** [comment]
@marckaraujo Just drop that runtime-line, as mentioned above (https://github.com/FibreFoX/javafx-gradle-plugin/issues/67#issuecomment-301708279)

You will have to have two separated machines, in case you don't want to shutdown gradle build daemons and change JAVA_HOME everytime.

It is not possible to generated 32bit with 64bit.

**Comment by FibreFoX** [comment]
@marckaraujo this still an issue for you?

**Comment by marckaraujo** [comment]
well, I cant generate the 32bits and 64bits with this library. So I am using "install4j" to do it. You can close the issue, thanks.
