### ISSUE TITLE
src/main/deploy must not be required

### ISSUE THREAD

**Issue by Lewik** [FibreFoX/javafx-gradle-plugin#7]
src/main/deploy must not be required
For example I have multiproject with gradle and there are no central project with src dir in root at all.

**Comment by FibreFoX** [comment]
Do you have anything on github I can reproduce/check with?

**Comment by Lewik** [comment]
I can't open sources of that multiproject.

For reproduce - just start "gradle jfxJar" without src/main/deploy and you catch "Adding 'deploy' directory wasn't successful, because it does not exist! (/Users/lewik/gts/scloader/src/main/deploy)
"

Hmmm... even without deploy dir I got jar files. So I think deploy dir isn't required.

But you need to add info about that deploy directory - what is this and for what is this.

**Comment by FibreFoX** [comment]
The deploy-dir is there to use the dropin-feature of the javafxpackager, you can replace some fileswith it, which would be gathered by internal tools.

If it's okay, I will close your tickets and reopen them as a "missing documentation" one ;)
