### ISSUE TITLE
How to redirect system out/err on launchers?

### ISSUE THREAD

**Issue by Pesegato** [FibreFoX/javafx-gradle-plugin#72]
I need to redirect System.out and System.err of the packaged application to a file. I've searched but couldn't find a way...

**Comment by FibreFoX** [comment]
This was already asked on StackOverflow:
https://stackoverflow.com/questions/31537869/write-to-console-from-a-native-javafx-app-created-with-inno-setup-and-maven/34476175#34476175

Workaround: create/compile your own native launcher-file using some redirects as described here:
https://stackoverflow.com/questions/311955/redirecting-cout-to-a-console-in-windows
https://bobobobo.wordpress.com/2009/03/01/how-to-attach-a-console-to-your-gui-app-in-c/

Background: the native launchers do not pipe these to the environment, you need to use a logging-framework or a different native launcher to get this.
