### ISSUE TITLE
For MSI, is uninstalling possible?

### ISSUE THREAD

**Issue by Pesegato** [FibreFoX/javafx-gradle-plugin#73]
Oracle docs don't mention it, so I guess it can't be provided... I've searched but found nothing about that.
MSI installed application (built with javadfx-gradle-plugin) don't even appear on Windows "installed application" (but they are present on start menu)

so... should I simply ignore the uninstalling?

**Comment by FibreFoX** [comment]
That sounds odd. If you install the application via MSI-installer, it will be registered inside windows application list, with the appName as entry.

**Comment by Pesegato** [comment]
Today I found the entry on the Windows panel, and was able to successfully uninstall the application. Some Windows error I guess...
