### ISSUE TITLE
linux(ubuntu) app icon

### ISSUE THREAD

**Issue by maPaydar** [FibreFoX/javafx-gradle-plugin#76]
where i must put icon image for ubuntu app icon ?

**Comment by FibreFoX** [comment]
Please set `verbose` to `true`, you will get some output what resources can be changed. For anything else please consult the official documentation of the `javapackager`. As far as I can recall, the app-icon on ubuntu has to be a special PNG-file.

**Comment by FibreFoX** [comment]
@maPaydar any feedback?

**Comment by maPaydar** [comment]
@FibreFoX thanks, put myapp.png in deploy/package/linux and then works.
