### ISSUE TITLE
Error invoking method/Starting JVM

### ISSUE THREAD

**Issue by jaytheking** [FibreFoX/javafx-gradle-plugin#82]
Im working on a windows based machine and running the jfxNative task generates the files okay i think but when running the executable i get the bellow error popup.

Im doing nothing special other than using the minimal gradle build

![image](https://user-images.githubusercontent.com/6914788/29439324-04f357aa-8411-11e7-9a61-55f8e84ed052.png)

**Comment by FibreFoX** [comment]
What happens when you run the jfx-jar from CLI? Mostly there are some unhandled exceptions or missing llibs.

**Comment by jaytheking** [comment]
This seems to be an issue for building the app on my linux box as well but running just the jar from command line gives:
```
jacques@Flatbread:~/Documents/GitHub/linesmarts-desktop/build/jfx/native/linesmarts-desktop-1.0-SNAPSHOT/app (master)$ ./project-jfx.jar 
com.linesmarts.model.ModelManager@4f28d398
```

No exceptions, same output for both windows and linux.

**Comment by FibreFoX** [comment]
Please execute your jfx-jar via `java -jar`, otherwise there is too much magic. The warning about the API-value might be ignorable, just a warning (but not related to this gradle-plugin).

Can you try to remove this line?
```
apply plugin: 'application'
``` 
It's not required when using this gradle-plugin, as you are not creating an application, but an javafx-bundle

**Comment by jaytheking** [comment]
```
jay@blackbox:~/Documents/GitHub/linesmarts-desktop (master) $ java -jar build/jfx/native/linesmarts-desktop-1.0-SNAPSHOT/app/project-jfx.jar
Aug 18, 2017 10:22:54 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.111 by JavaFX runtime of version 8.0.60
Aug 18, 2017 10:22:55 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.111 by JavaFX runtime of version 8.0.60
com.linesmarts.model.ModelManager@60961404
```
Same output running with `java -jar`

Ive attached the project in it's current state with the changes mentioned above. The JAR runs fine it seems just not any of the native stuff. Im 100% sure its not my platform as ive cloned your sample projects and they all work fine even with having fxml files for views. My project doesnt differ in terms of directory structure.

[linesmarts-desktop.zip](https://github.com/FibreFoX/javafx-gradle-plugin/files/1234153/linesmarts-desktop.zip)

**Comment by FibreFoX** [comment]
I can reproduce this on Windows, maybe I can find this piece of trouble ;)

**Comment by FibreFoX** [comment]
Can you try to change the following code:
```java

    public static void main(String[] args) {
        WindowManager.setModelManager( getEmptyModelManager() );
        launch( args );
    }
```
Please move `WindowManager.setModelManager( getEmptyModelManager() );` away from the main method, after that the binary worked for me .... strange

**Comment by jaytheking** [comment]
> Can you try to change the following code:
> 
>     public static void main(String[] args) {
>         WindowManager.setModelManager( getEmptyModelManager() );
>         launch( args );
>     }
> Please move WindowManager.setModelManager( getEmptyModelManager() ); away from the main method, after that the binary worked for me .... strange

Where did you move it to? Because now im getting slightly different error now.
```
jay@blackbox:~/Documents/GitHub/linesmarts-desktop/build/jfx/native/linesmarts-desktop-1.0-SNAPSHOT (master) $ sudo ./linesmarts-desktop-1.0-SNAPSHOT
[sudo] password for jay: 
linesmarts-desktop-1.0-SNAPSHOT Class com/linesmarts/Main not found.
linesmarts-desktop-1.0-SNAPSHOT Failed to launch JVM
```

**Comment by FibreFoX** [comment]
In that "Main"-class, I moved that line to the `start()` method ... maybe your code differs from the stuff you attached here?

**Comment by jaytheking** [comment]
> Please move WindowManager.setModelManager( getEmptyModelManager() ); away from the main method, after that the binary worked for me .... strange.
> 
> After moving this call into the start(Stage stage)-method seems to work for me.


Ok moving that call to start() method fixes issues for windows and now runs fine. Only fails on linux build now with this error still:
```
jay@blackbox:~/Documents/GitHub/linesmarts-desktop/build/jfx/native/linesmarts-desktop-1.0-SNAPSHOT (master) $ sudo ./linesmarts-desktop-1.0-SNAPSHOT
[sudo] password for jay: 
linesmarts-desktop-1.0-SNAPSHOT Class com/linesmarts/Main not found.
linesmarts-desktop-1.0-SNAPSHOT Failed to launch JVM
```

**Comment by FibreFoX** [comment]
Did you clean the "build"-folder? Maybe it's some recompile-issue? ;)

**Comment by jaytheking** [comment]
> Did you clean the "build"-folder? Maybe it's some recompile-issue? ;)

Did a full clean and jfxNative build and still same issue.

**Comment by FibreFoX** [comment]
Thats odd. What JDK are you using on your systems? It seems that your Windows- and your Linux-system do not have the same version.

**Comment by jaytheking** [comment]
```
jay@blackbox:~ $ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
jay@blackbox:~ $ javac -version
javac 1.8.0_131
jay@blackbox:~ $ 
```

**Comment by jaytheking** [comment]
> jay@blackbox:~ $ java -version
> openjdk version "1.8.0_131"
> OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
> OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
> jay@blackbox:~ $ javac -version
> javac 1.8.0_131
> jay@blackbox:~ $

So this is weird, my desktop(Linux) is the only one that does not properly build the app for linux native. I took the same repo i linked earlier and built it on my laptop with the other change you recommended and it build fine and runs.

I suppose you can close the issue now but im still unsure why it doesnt build on my desktop.

**Comment by FibreFoX** [comment]
Okay, will close this issue. If you find something, just drop some lines so others can find it via search.

But yes, it really is strange that there is a different behaviour.

**Comment by prog110** [comment]
I'm facing exactly the same issue in Ubuntu 16.04

My java version is
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

Any idea on how to resolve this issue?
