### ISSUE TITLE
Using javafx-gradle-plugin using Kotlin dsl

### ISSUE THREAD

**Issue by hanct** [FibreFoX/javafx-gradle-plugin#86]
Hi,
This is my first time trying to use javafx-gradle-plugin.  Is there any sample code on this git hub that shows how to do the equivalent of the below, but using KOTLIN dsl , instead of groovy dsl?

jfx {
    verbose = true
    mainClass = 'ru.mc.ltec.MainClass'
    
}

**Comment by FibreFoX** [comment]
Not yet, but as I don't know kotlin, I can't assist here, but shouldn't be too hard.

**Comment by hanct** [comment]
Thanks for reply. Manage to workout myself. 

extensions.getByType(JavaFXGradlePluginExtension::class.java).apply{
    mainClass="sg.xdocx.Main"
    vendor ="vendorName"
}
