### ISSUE TITLE
Msvcr100.dll missing in Windows 10 generation

### ISSUE THREAD

**Issue by giloutho** [FibreFoX/javafx-gradle-plugin#87]
Many thanks for your great plugin. I have a JavaFX project with three OS targets.

I develop on a Mac with Netbeans. Project is cloned on Linux and Windows 10 with Netbeans to check the proper functioning of the program. No problems on Mac and Linux. 

I made a first generation of windows installer on Windows 7 64 with Innosetup. No problems, it's working. Unfortunately, this computer has crashed. I have now  a new PC with Windows 10. With the same approach, Netbeans cloning, Gradle and Innosetup, I made a jfxnative generation (java 1.8.0_151 Gradle 4.3). The installer don't run wtih this message :  _Failed to find library : ...bin\server\server\jvm.dll._ 

If I run on W10 computer the first bundle (W7), it's running perfectlyr. I observed differences in bundles :

Bundle W7 in the folder native/appname/ there is :
- msvcp120.dll
- msvcr100.dll
- msvcr120.dll
- packager.dll.

Bundle W10 in the folder native/appname/ there is :
- msvcp140.dll
- packager.dll
- vcruntime140.dll

If I put msvcr100.dll in the folder of the application (..\AppData\Local\appname\), application works.
 
While I put msvcr100.dll in windows\system32, this dll is not copied in the folder native/appname during gradle jfxnative operation. 

Do you have an idea ?

**Comment by FibreFoX** [comment]
As far as I can see, this is a problem of the underlying `javapackager`:
http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/32f0fd77356c/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinAppBundler.java#l75
In some previous version, the copied files were different ones:
http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/88934563bc8e/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinAppBundler.java#l75

It seems that they are using VC14 now for generating these binary files, and therefore the runtimes might have changed.

Which is a bit confusing is this piece: `The installer don't run wtih this message : Failed to find library : ...bin\server\server\jvm.dll.` do you really mean the INSTALLER, or do you mean the native launcher?

**Comment by giloutho** [comment]
Sorry, I mean native launcher.

I only need msvcr100.dll. In both lines of your links we find it.

Actually, if I put msvcr100.dll beside msvcp140.dll,packager.dll and vcruntime140.dll it's working. I tried to use additionalBundlerResources. 

I create a folder bundlers where I put msvcr100.dll and in build.gradle, I put 
_jfx {
...
      additionalBundlerResources = 'src/main/bundlers'
 }_
But it does not work.

**Comment by FibreFoX** [comment]
The point is, if this is a generic problem, this is should be an open bug on the official oracle java bug-system. I need some time to pinpoint the problem.

**Comment by giloutho** [comment]
Thank you for being so available and so kind.

I tried many solutions including installation of different Visual C++ redistributable packages without success.

For now :
- a native launcher is generated by javafx-gradle-plugin
- I add msvcr100.dll beside msvcp140.dll, packager.dll and vcruntime140.dll
- I create an Innosetup script to create a new package of this.

It seems to work well.

**Comment by giloutho** [comment]
Hi,

It's very strange. Today, I want to make a new release, I run a jfxnative on the Windows machine. With surprise, the bundle is good without msvcr100.dll. I delete all copies of this dll on the computer and this is still good.

Only one explanation : between our messages, Windows 10 was updated.

**Comment by FibreFoX** [comment]
Thats really strange ... good news that you got it working, but it has a bad aftertaste. Do you mind if I close this issue? My plans are to publish new JDK9-versions for christmas or new years eve, and as I'm developing on Win10, I will reopen this if I hit this again.

**Comment by giloutho** [comment]
For instant, you can close... I wish you success in your efforts for JDK9 versions
