### ISSUE TITLE
Multi-Module JavaFX Project

### ISSUE THREAD

**Issue by Zoha131** [FibreFoX/javafx-gradle-plugin#89]
Please share multimodule project example. I have googled but failed to get any appropriate solution.

BTW, I am not sure this request should be on issues or not.

**Comment by FibreFoX** [comment]
Making this an issue is probably the best way, as some project watchers can answer to such questions too. With "multi-module-project example" do you mean the new JDK 9 modules?

**Comment by FibreFoX** [comment]
ping @Zoha131

**Comment by Zoha131** [comment]
Ok, I am a very beginner level programmer. My question was about multi-package. But by that time my understanding about package and module was not clear. So I wrote module instead of package. It was my mistake.
BTW I have failed to use this plugin in my multi-package project. It would be helpful for me if this project shares any tutorial or documentation.

**Comment by FibreFoX** [comment]
Ah, okay :) no problem.

Before I'm starting to point into the wrong direction, just let me give you, what I'm suspecting you want to do: You want to create a gradle-project, where you can have different "subprojects" which are bundled into a single project, is that correct? You idea is to have separated jar-files which contain fragments of the whole application, right?

**Comment by Zoha131** [comment]
At first, I thought exactly what you have suspected. But later, I realized that the project was simple enough. And didn't mess up with Gradle. I built my project using IntelliJ Idea's default packaging feature.

Here is my project structure.......
![24796404_1983493448567609_864914910580387882_n](https://user-images.githubusercontent.com/16666716/36319590-961daf46-136d-11e8-87b2-d5dc79f0112c.jpg)

**Comment by FibreFoX** [comment]
Oh, it seems that you missed some convention about java-projects. All java-files, which are going to be compiled, belong to `src/main/java/`, other resources (like the fxml-files) belong below `src/main/resources/`. This is a common and widely used convention (I think this came from maven, but not sure). I now do understand why you said "multiple packages".

All in all, this is no issue with the plugin. See this example: https://github.com/FibreFoX/javafx-gradle-plugin/tree/master/examples/minimal-setup-jfxjar

**Comment by Zoha131** [comment]
This was my first ever project. I might have misinformed you. Sorry for bothering you. I have just started learning java technology and I have a long way to go. And thanks for your time.

**Comment by FibreFoX** [comment]
No worries :) everyones road is filled with stones. I just hope my information got you some ideas how to work with this plugin.
