### ISSUE TITLE
identifier doesn't get used when building .msi

### ISSUE THREAD

**Issue by swpalmer** [FibreFoX/javafx-gradle-plugin#91]
As I understand it 'identifier' should be used as the UpgradeCode for the .msi.  This isn't happening.  The generated .wxs file shows a new GUID each time the build is done.

**Comment by FibreFoX** [comment]
I think what you are searching for is some entry inside `bundleArguments`: "win.msi.upgradeUUID"


```java
// copied from WinMsiBundler.java
    public static final BundlerParamInfo<UUID> UPGRADE_UUID = new WindowsBundlerParam<>(
            I18N.getString("param.upgrade-uuid.name"),
            I18N.getString("param.upgrade-uuid.description"),
            "win.msi.upgradeUUID",
            UUID.class,
            params -> UUID.randomUUID(), // TODO check to see if identifier is a valid UUID during default
            (s, p) -> UUID.fromString(s));
```

**Comment by swpalmer** [comment]
Yes.  I also dug through the source code and found the same line.  Note the TODO comment indicating that 'identifier' is supposed to be used as the default value for win.msi.upgradeUUID but it isn't.  'identifier' is documented, the 'win.msi.upgradeUUID' property isn't

**Comment by FibreFoX** [comment]
@swpalmer as far as I understood, this issue could be closed. Please comment otherwise in case I misinterpreted your answer
