### ISSUE TITLE
Application version name is not reflected in application.exe file

### ISSUE THREAD

**Issue by sjadaun** [FibreFoX/javafx-gradle-plugin#94]
Hi,

I'm using custom Inno setup file to package my application(since some of options i want to use are not present in template.iss used by javapackager) i'm trying to generate the setup file name as "project-version.exe" but there is not way for me to get the version from gradle to Innosetup script. 

Simplest way for me would be to get version infomation form exe file using GetFileVesrsion("application.exe") but that always returns empty since the standalone application never has application info.

not sure i'm its a bug or i'm missing something. 

following is my Gradle script:
```
jfx {
    verbose = true
    mainClass = 'com.celp.Main'
    jfxAppOutputDir = "build/jfx/app"
    jfxMainAppJarName = 'celp.jar'
    deployDir = "src/main/deploy"  //this is where icon and custom .iss file is
    useEnvironmentRelativeExecutables = true
    libFolderName = 'libs'
    jvmArgs = ['-verbose:gc' , '-Xmx1024m',  '-XX:+PrintTenuringDistribution',]

    nativeReleaseVersion = fullVersionString  //full version string i need in .iss file
    skipNativeVersionNumberSanitizing = true
    bundler = 'exe'
    nativeOutputDir = "build/jfx/native"
    appName = "celp"
}
```

This is how i'm trying to get version info in .iss 

```
#define MyAppName "celp"
#define ApplicationVersion GetFileVersion('celp/celp.exe')
OutputBaseFilename={#MyAppName}-{#MyAppVersion} 
```

Currently I have create workaround with creating a file with version number in it in (celp/verison.txt) in gradle and then read version info from that file in Innosetup.iss script. Although i don't prefer this way.

I tested with default iss file as well, then final outfile setup file is created with expected name (celp-version.exe) but the main exe(celp.exe) still doesn't have version information.

**Comment by FibreFoX** [comment]
Do you need the version inside your application? If so, you might want to create a property-file containing that version (maybe using [some resource-filtering](https://stackoverflow.com/a/25328289/1961102) or creating/overwriting from inside gradle).

Setting things from the EXE-file weren't prepared for customization, but this might change with JDK 9, I saw some changes regarding file-information.

**Comment by sjadaun** [comment]
I am doing exactly that for getting information inside application. issue is at the build time. 
Basically for me build number included in version is generated by jenkins and I don't see any good way to get that number to InnoSetup.iss file, which will generate final installation file.

Currently as I said, i just generate a temp file from gradle, copy that to build folder using additionalAppResources and when packaging read version info from file to InnoSetup.iss variable and exclude that file from packaging. 

Not sure if this works with Ant build, but information should be visible when we see property  of exe file in windows.
Even with the inbuilt Intellij artifact generator this comes empty as well. Could be issue with java packager for windows.
 
I tried building the same in Ubuntu without any changes and it works as excepted. 
I think it would is issue with windows packager. As you said hope it will be fixed in JDK9

I will close this as this doesnt seems to be issue with plugin. I will use the workaround for now.
