### ISSUE TITLE
Generating native with Gradle's "implementation" dependency configuration

### ISSUE THREAD

**Issue by frnusmartobjects** [FibreFoX/javafx-gradle-plugin#95]
We have a project that we are updating to use the "new" configurations to declare dependencies, such as `implementation` or `api`. No matter what we use, when we try to execute the generated ".exe" file by the jfxNative task, the application can't find the main class. But if we use the traditional `compile` then it works perfectly.

Is it possible to generate working native ".exe" using the "implementation" keyword for dependency configuration of Gradle?

**Comment by FibreFoX** [comment]
As I'm not up2date with new gradle-development, can you point me some URL to the documentation for this?

**Comment by frnusmartobjects** [comment]
The first reference you can use is this
https://docs.gradle.org/current/userguide/java_library_plugin.html
Even though this is for the java library plugin it does contains the pertinent information, specifically in sections: 

* 49.2. API and implementation separation
* 49.4. The Java Library plugin configurations

**Comment by BoGnY** [comment]
Another good link is [android gradle plugin v3.0.0 migration](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html), especially section "Use the new dependency configurations".

New dependency configuration was introduced with Gradle version 3.4, now on version 4.x are deprecated, and from version 5.0 will be deleted...

**Comment by FibreFoX** [comment]
Now I'm starting to get what is going on 😺 

You are talking about some special project-style, this plugin does base on the `java`-plugin, not the `java-library`-plugin, therefor the `compile`-configuration is NOT deprecated, but just for that plugin/project-style.


> The compile, testCompile, runtime and testRuntime configurations **inherited from the Java plugin** are still available but are deprecated. You should avoid using them, as they are only kept for backwards compatibility.
