### ISSUE TITLE
All custom and personal task are not executed

### ISSUE THREAD

**Issue by BoGnY** [FibreFoX/javafx-gradle-plugin#99]
Hi, I've setup successfully a simple build.gradle file, but if I add a custom task (which must been execute as latest), was done as first, or was never done...

Can someone help me?

```gradle
buildscript {
    dependencies {
        classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: '8.8.2'
    }
    repositories {
        mavenLocal()
        mavenCentral()
    }
}
apply plugin: 'java'
apply plugin: 'eclipse'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile 'org.apache.logging.log4j:log4j-api:2.10.0'
    compile 'org.apache.logging.log4j:log4j-core:2.10.0'
    compile 'org.xerial:sqlite-jdbc:3.21.0.1'
    compile 'commons-io:commons-io:2.6+'
}

apply plugin: 'javafx-gradle-plugin'

def outputDir = 'build'

jfx {
    mainClass = 'it.bogny.jyugiohdb.MainApp'
    jfxAppOutputDir = outputDir + '/jfx'
    jfxMainAppJarName = 'jyugiohdb.jar'
    vendor = 'BoGnY'
    manifestAttributes = [
        "Built-By": "BoGnY",
    ]
}

task copyDependencies(dependsOn: jfxJar, type: Copy) {
    doLast {
        println 'Copy dependencies and other mandatory files to build dir.'
        from('./') {
            include 'yugiohdb_empty.db'
        }
        into outputDir
        rename { String fileName ->
            fileName.replace('_empty', '')
        }
    }
}
```

With this script, task was never done...

And if I try to add this as last line `copyDependencies.dependsOn jfxJar`, task was done at first... :confused: :confused:

I have Win10 64bit, with Eclipse IDE and latest Gradle v4.4.1.

Thanks for help

**Comment by BoGnY** [comment]
After a few hours of investigation, I can say that the problem is in the row `copyDependencies.dependsOn jfxJar` since the plugin, after executing the `:jfxJar` command (and I also think the `:jfxRun` command), **no longer performs any other task**...

Therefore, my custom task which must be executed after that command, will never be executed..

**Comment by FibreFoX** [comment]
I know it might sound too lazy, but can you provide me some small project, where I can reproduce this? Don't have that much time currently, but working on getting more time for my spare time projects again.

**Comment by BoGnY** [comment]
Hi, I have made a small project: https://github.com/BoGnY/JavaFX-Gradle-Plugin-Issue99-Example

If you start task _:jfxJar_ the output of task order it is:
> :copyDependencies
> :createVersionString
> :compileJava
> :processResources
> :classes
> :jar
> :jfxJar

but it would be:
> :compileJava
> :processResources
> :classes
> :jar
> :createVersionString
> :copyDependencies
> :jfxJar

As it is writed in [line 70 of build.gradle](https://github.com/BoGnY/JavaFX-Gradle-Plugin-Issue99-Example/blob/master/build.gradle#L70), it is _:jfxJar_ that depends by _:createVersionString_ and _:copyDependencies_ in this order, and not all project that depends by this two tasks....

To do tasks with almost correctly order, I have writed unnecessary _:buildJfxJarWithDep_ example task, and added a few lines for configure it as you can see in [line 74-76 of build.gradle](https://github.com/BoGnY/JavaFX-Gradle-Plugin-Issue99-Example/blob/0f7ee9f0cb616340ad16a2f24637b38d2a831af1/build.gradle#L74-L76)..
If you delete comment in [line 73](https://github.com/BoGnY/JavaFX-Gradle-Plugin-Issue99-Example/blob/0f7ee9f0cb616340ad16a2f24637b38d2a831af1/build.gradle#L73) and [line 77](https://github.com/BoGnY/JavaFX-Gradle-Plugin-Issue99-Example/blob/0f7ee9f0cb616340ad16a2f24637b38d2a831af1/build.gradle#L77), and start _:buildJfxJarWithDep_ task, the task order will be almost correctly:
> :createVersionString
> :compileJava
> :processResources
> :classes
> :jar
> :jfxJar
> :copyDependencies
> :buildJfxJarWithDep

From what I see and I understand, your plugin don't handle correctly dependsOn() Gradle function, because if on build script I write `jfxJar.dependsOn createVersionString /*(as first)*/, copyDependencies /*(as second)*/` the order that I expect would be:
> :compileJava
> :processResources
> :classes
> :jar
> :createVersionString (as first)
> :copyDependencies (as second)
> :jfxJar

I hope it can help you,
BoGnY

**Comment by FibreFoX** [comment]
I have an example, which does work:
https://github.com/FibreFoX/javafx-gradle-plugin/blob/master/examples/javafx-proguard-gradle/build.gradle

hm ... but it seems that "dependsOn" is working in the different direction than you might think? `jfxJar.dependsOn myProguardTask`

**Comment by FibreFoX** [comment]
Ping @bogny

**Comment by FibreFoX** [comment]
ping @BoGnY
